In [18]:
import pandas as pd

In [19]:
import pandas as pd
df = pd.read_csv("../data/sample_emails.csv")
df.head()

,id,sender,subject,body,priority,label
0,1,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,important
1,2,noreply@shopping.com,Big Billion Sale is Live,Flat 70% OFF on electronics. Limited period of...,low,promotion
2,3,alerts@mybank.com,Unusual Login Attempt,We detected a login attempt to your account fr...,high,security
3,4,newsletter@blog.com,Weekly Tech Newsletter,"In this week's edition, learn about AI agents,...",low,newsletter
4,5,friend123@gmail.com,Coffee this weekend?,"Hey, long time no see! Are you free this weeke...",medium,personal

In [20]:
df.describe(include="all")

,id,sender,subject,body,priority,label
count,8.00000,8,8,8,8,8
unique,NaN,8,8,8,3,7
top,NaN,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,work
freq,NaN,1,1,1,4,2
mean,4.50000,NaN,NaN,NaN,NaN,NaN
std,2.44949,NaN,NaN,NaN,NaN,NaN
min,1.00000,NaN,NaN,NaN,NaN,NaN
25%,2.75000,NaN,NaN,NaN,NaN,NaN
50%,4.50000,NaN,NaN,NaN,NaN,NaN
75%,6.25000,NaN,NaN,NaN,NaN,NaN
max,8.00000,NaN,NaN,NaN,NaN,NaN

In [21]:
df["label"].value_counts()

label
work          2
important     1
promotion     1
security      1
newsletter    1
personal      1
spam          1
Name: count, dtype: int64

In [22]:
df.fillna("")

,id,sender,subject,body,priority,label
0,1,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,important
1,2,noreply@shopping.com,Big Billion Sale is Live,Flat 70% OFF on electronics. Limited period of...,low,promotion
2,3,alerts@mybank.com,Unusual Login Attempt,We detected a login attempt to your account fr...,high,security
3,4,newsletter@blog.com,Weekly Tech Newsletter,"In this week's edition, learn about AI agents,...",low,newsletter
4,5,friend123@gmail.com,Coffee this weekend?,"Hey, long time no see! Are you free this weeke...",medium,personal
5,6,spam@strange-domain.ru,"You won $1,000,000!!!",Click here to claim your lottery now. Do not s...,high,spam
6,7,manager@company.com,Project Update Required,Please share the status update of your project...,high,work
7,8,training@lms.com,Reminder: Complete Mandatory Training,Your mandatory security awareness training is ...,medium,work

In [23]:
df = df.fillna("")
df['subject'] = df['subject'].str.lower().str.strip()
df['body'] = df['body'].str.lower().str.strip()
print(df)

   id                  sender                                subject  \
0   1          hr@company.com             offer letter - please sign
1   2    noreply@shopping.com               big billion sale is live
2   3       alerts@mybank.com                  unusual login attempt
3   4     newsletter@blog.com                weekly  tech newsletter
4   5     friend123@gmail.com                   coffee this weekend?
5   6  spam@strange-domain.ru                  you won $1,000,000!!!
6   7     manager@company.com                project update required
7   8        training@lms.com  reminder: complete mandatory training

                                                body priority       label
0  dear candidate, congratulations! please sign a...     high   important
1  flat 70% off on electronics. limited period of...      low   promotion
2  we detected a login attempt to your account fr...     high    security
3  in this week's edition, learn about ai agents,...      low  newsletter
4  hey, long time no see! are you free this weeke...   medium    personal
5  click here to claim your lottery now. do not s...     high        spam
6  please share the status update of your project...     high        work
7  your mandatory security awareness training is ...   medium        work

In [24]:
df['combined'] = df['subject'] + " " + df['body']

In [25]:
offer_only = df[df['combined'].str.contains("offer")]

print(df)
print("\nOffer Messages:")
print(offer_only)

   id                  sender                                subject  \
0   1          hr@company.com             offer letter - please sign
1   2    noreply@shopping.com               big billion sale is live
2   3       alerts@mybank.com                  unusual login attempt
3   4     newsletter@blog.com                weekly  tech newsletter
4   5     friend123@gmail.com                   coffee this weekend?
5   6  spam@strange-domain.ru                  you won $1,000,000!!!
6   7     manager@company.com                project update required
7   8        training@lms.com  reminder: complete mandatory training

                                                body priority       label  \
0  dear candidate, congratulations! please sign a...     high   important
1  flat 70% off on electronics. limited period of...      low   promotion
2  we detected a login attempt to your account fr...     high    security
3  in this week's edition, learn about ai agents,...      low  newsletter
4  hey, long time no see! are you free this weeke...   medium    personal
5  click here to claim your lottery now. do not s...     high        spam
6  please share the status update of your project...     high        work
7  your mandatory security awareness training is ...   medium        work

                                            combined
0  offer letter - please sign dear candidate, con...
1  big billion sale is live flat 70% off on elect...
2  unusual login attempt we detected a login atte...
3  weekly  tech newsletter in this week's edition...
4  coffee this weekend? hey, long time no see! ar...
5  you won $1,000,000!!! click here to claim your...
6  project update required please share the statu...
7  reminder: complete mandatory training your man...

Offer Messages:
   id                sender                     subject  \
0   1        hr@company.com  offer letter - please sign
1   2  noreply@shopping.com    big billion sale is live

                                                body priority      label  \
0  dear candidate, congratulations! please sign a...     high  important
1  flat 70% off on electronics. limited period of...      low  promotion

                                            combined
0  offer letter - please sign dear candidate, con...
1  big billion sale is live flat 70% off on elect...

In [26]:
important_only = df[df['label'].str.contains("important")]
print(important_only)

   id          sender                     subject  \
0   1  hr@company.com  offer letter - please sign

                                                body priority      label  \
0  dear candidate, congratulations! please sign a...     high  important

                                            combined
0  offer letter - please sign dear candidate, con...

In [27]:
df.shape

(8, 7)

In [28]:
df.isnull().sum()

id          0
sender      0
subject     0
body        0
priority    0
label       0
combined    0
dtype: int64

In [29]:
df['priority'].value_counts()

priority
high      4
low       2
medium    2
Name: count, dtype: int64

In [30]:
df.columns

Index(['id', 'sender', 'subject', 'body', 'priority', 'label', 'combined'], dtype='object')

In [31]:
df['clean text']=df['body' ].str.lower().str.replace('[^a-zA-Z]','', regex=True)

In [52]:
print(df['clean text'])

0    dearcandidatecongratulationspleasesignanduploa...
1    flatoffonelectronicslimitedperiodoffervisitour...
2    wedetectedaloginattempttoyouraccountfromanewde...
3    inthisweekseditionlearnaboutaiagentslanggrapha...
4       heylongtimenoseeareyoufreethisweekendforcoffee
5    clickheretoclaimyourlotterynowdonotsharethiswi...
6    pleasesharethestatusupdateofyourprojectbeforep...
7    yourmandatorysecurityawarenesstrainingisduetom...
Name: clean text, dtype: object

In [50]:
df['priority'].value_counts()

priority
high      4
low       2
medium    2
Name: count, dtype: int64

In [51]:
print(df.shape)

(8, 8)

In [49]:
from collections import Counter
all_words = "".join(df['clean text'])
word_list = all_words.split()
word_freq = Counter(word_list)
word_freq.most_common(15)

[('dearcandidatecongratulationspleasesignanduploadyourofferletterbytodayeveningflatoffonelectronicslimitedperiodoffervisitourstorenowwedetectedaloginattempttoyouraccountfromanewdeviceifthiswasnotyoupleaseresetyourpasswordinthisweekseditionlearnaboutaiagentslanggraphandmoreheylongtimenoseeareyoufreethisweekendforcoffeeclickheretoclaimyourlotterynowdonotsharethiswithanyonepleasesharethestatusupdateofyourprojectbeforepmtodayyourmandatorysecurityawarenesstrainingisduetomorrow',
  1)]

In [32]:
df[['body','clean text']].head()

,body,clean text
0,"dear candidate, congratulations! please sign a...",dearcandidatecongratulationspleasesignanduploa...
1,flat 70% off on electronics. limited period of...,flatoffonelectronicslimitedperiodoffervisitour...
2,we detected a login attempt to your account fr...,wedetectedaloginattempttoyouraccountfromanewde...
3,"in this week's edition, learn about ai agents,...",inthisweekseditionlearnaboutaiagentslanggrapha...
4,"hey, long time no see! are you free this weeke...",heylongtimenoseeareyoufreethisweekendforcoffee

In [47]:
from collections import Counter
all_words = "".join(df['clean text'])
word_list = all_words.split()
word_freq = Counter(word_list)
word_freq.most_common(15)

[('dearcandidatecongratulationspleasesignanduploadyourofferletterbytodayeveningflatoffonelectronicslimitedperiodoffervisitourstorenowwedetectedaloginattempttoyouraccountfromanewdeviceifthiswasnotyoupleaseresetyourpasswordinthisweekseditionlearnaboutaiagentslanggraphandmoreheylongtimenoseeareyoufreethisweekendforcoffeeclickheretoclaimyourlotterynowdonotsharethiswithanyonepleasesharethestatusupdateofyourprojectbeforepmtodayyourmandatorysecurityawarenesstrainingisduetomorrow',
  1)]

In [33]:
all_words_text = " ".join(df['clean text'])

In [34]:
words=all_words_text.split()

In [35]:
pip install nltk

Requirement already satisfied: nltk in /Users/nitishrmaladakar/anaconda3/envs/new_plant_env/lib/python3.11/site-packages (3.9.2)
Requirement already satisfied: click in /Users/nitishrmaladakar/anaconda3/envs/new_plant_env/lib/python3.11/site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /Users/nitishrmaladakar/anaconda3/envs/new_plant_env/lib/python3.11/site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in /Users/nitishrmaladakar/anaconda3/envs/new_plant_env/lib/python3.11/site-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /Users/nitishrmaladakar/anaconda3/envs/new_plant_env/lib/python3.11/site-packages (from nltk) (4.67.1)
Note: you may need to restart the kernel to use updated packages.

In [36]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
filtered_words = [w for w in words if w not in stop_words]

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/nitishrmaladakar/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [38]:
print("\n--- Final Word List (First 10) ---")
print(filtered_words[:10])

--- Final Word List (First 10) ---
['dearcandidatecongratulationspleasesignanduploadyourofferletterbytodayevening', 'flatoffonelectronicslimitedperiodoffervisitourstorenow', 'wedetectedaloginattempttoyouraccountfromanewdeviceifthiswasnotyoupleaseresetyourpassword', 'inthisweekseditionlearnaboutaiagentslanggraphandmore', 'heylongtimenoseeareyoufreethisweekendforcoffee', 'clickheretoclaimyourlotterynowdonotsharethiswithanyone', 'pleasesharethestatusupdateofyourprojectbeforepmtoday', 'yourmandatorysecurityawarenesstrainingisduetomorrow']

In [40]:
from collections import Counter
word_counts = Counter(filtered_words)

In [41]:
print(word_counts)

Counter({'dearcandidatecongratulationspleasesignanduploadyourofferletterbytodayevening': 1, 'flatoffonelectronicslimitedperiodoffervisitourstorenow': 1, 'wedetectedaloginattempttoyouraccountfromanewdeviceifthiswasnotyoupleaseresetyourpassword': 1, 'inthisweekseditionlearnaboutaiagentslanggraphandmore': 1, 'heylongtimenoseeareyoufreethisweekendforcoffee': 1, 'clickheretoclaimyourlotterynowdonotsharethiswithanyone': 1, 'pleasesharethestatusupdateofyourprojectbeforepmtoday': 1, 'yourmandatorysecurityawarenesstrainingisduetomorrow': 1})

In [43]:
freq_df = pd.DataFrame(word_counts.items(), columns=['Word', 'Count'])


freq_df = freq_df.sort_values(by='Count', ascending=False).reset_index(drop=True)

print("\n--- Top 10 Most Frequent Words ---")
print(freq_df.head(10))

--- Top 10 Most Frequent Words ---
                                                Word  Count
0  dearcandidatecongratulationspleasesignanduploa...      1
1  flatoffonelectronicslimitedperiodoffervisitour...      1
2  wedetectedaloginattempttoyouraccountfromanewde...      1
3  inthisweekseditionlearnaboutaiagentslanggrapha...      1
4     heylongtimenoseeareyoufreethisweekendforcoffee      1
5  clickheretoclaimyourlotterynowdonotsharethiswi...      1
6  pleasesharethestatusupdateofyourprojectbeforep...      1
7  yourmandatorysecurityawarenesstrainingisduetom...      1

In [53]:
df["combined"] = (df["subject"] + " " + df["body"]).str.lower()
categories = {
    "important": ["offer", "offer letter", "please sign", "upload"],
    "promotion": ["sale", "off", "discount", "flat", "limited period"],
    "security": ["login", "login attempt", "account", "password", "detected"],
    "newsletter": ["newsletter", "weekly", "edition", "subscribe"],
    "personal": ["coffee", "weekend", "hey", "long time"],
    "spam": ["won", "lottery", "claim", "click here", "prize"],
    "work": ["project", "status update", "please share", "reminder", "training"]
}
def detect_simple(text):
    text = text.lower()
    matches = []
    for cat, keys in categories.items():
        for k in keys:
            if k in text:
                matches.append(cat)
                break
    return matches

df["matched"] = df["combined"].apply(detect_simple)
df["num_matches"] = df["matched"].apply(len)
df[["id","subject","matched","num_matches"]]
from collections import Counter
category_counts = Counter()
for lst in df["matched"]:
    for c in lst:
        category_counts[c] += 1

category_counts

Counter({'promotion': 3,
         'important': 2,
         'work': 2,
         'security': 1,
         'newsletter': 1,
         'personal': 1,
         'spam': 1})