In [241]:
print("This is pandas")

This is pandas

In [242]:
import pandas as pd
df=pd.read_csv("../data/sample_emails.csv")
df.head()

,id,sender,subject,body,priority,label
0,1,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign and upload your offer letter by today evening.",high,important
1,2,noreply@shopping.com,Big Billion Sale is Live,Flat 70% OFF on electronics. Limited period offer. Visit our store now.,low,promotion
2,3,alerts@mybank.com,Unusual Login Attempt,"We detected a login attempt to your account from a new device. If this was not you, please reset your password.",high,security
3,4,newsletter@blog.com,Weekly Tech Newsletter,"In this week's edition, learn about AI agents, LangGraph, and more.",low,newsletter
4,5,friend123@gmail.com,Coffee this weekend?,"Hey, long time no see! Are you free this weekend for coffee?",medium,personal

In [243]:
df.info

<bound method DataFrame.info of    id                  sender                                subject  \
0   1          hr@company.com             Offer Letter - Please Sign
1   2    noreply@shopping.com               Big Billion Sale is Live
2   3       alerts@mybank.com                  Unusual Login Attempt
3   4     newsletter@blog.com                 Weekly Tech Newsletter
4   5     friend123@gmail.com                   Coffee this weekend?
5   6  spam@strange-domain.ru                  You won $1,000,000!!!
6   7     manager@company.com                Project Update Required
7   8        training@lms.com  Reminder: Complete Mandatory Training

                                                                                                              body  \
0                      Dear Candidate, Congratulations! Please sign and upload your offer letter by today evening.
1                                          Flat 70% OFF on electronics. Limited period offer. Visit our store now.
2  We detected a login attempt to your account from a new device. If this was not you, please reset your password.
3                                              In this week's edition, learn about AI agents, LangGraph, and more.
4                                                     Hey, long time no see! Are you free this weekend for coffee?
5                                             Click here to claim your lottery now. Do not share this with anyone.
6                                                Please share the status update of your project before 5 PM today.
7                                                      Your mandatory security awareness training is due tomorrow.

  priority       label
0     high   important
1      low   promotion
2     high    security
3      low  newsletter
4   medium    personal
5     high        spam
6     high        work
7   medium        work  >

In [244]:
df["label"].value_counts()

label
work          2
promotion     1
important     1
security      1
newsletter    1
personal      1
spam          1
Name: count, dtype: int64

In [245]:
print(df.columns)

Index(['id', 'sender', 'subject', 'body', 'priority', 'label'], dtype='object')

In [246]:
import re
def clean(x):
    if pd.isna(x):
        return ""
    x = x.lower().strip()
    x = re.sub(r'\s+', ' ', x)
    x = re.sub(r'[^\w\s@.?]', '', x)
    return x

text_cols = ['sender', 'subject', 'body', 'priority', 'label']

for col in text_cols:
    df[col] = df[col].apply(clean)

In [247]:
pd.set_option('display.max_colwidth', None)
display(df)

,id,sender,subject,body,priority,label
0,1,hr@company.com,offer letter please sign,dear candidate congratulations please sign and upload your offer letter by today evening.,high,important
1,2,noreply@shopping.com,big billion sale is live,flat 70 off on electronics. limited period offer. visit our store now.,low,promotion
2,3,alerts@mybank.com,unusual login attempt,we detected a login attempt to your account from a new device. if this was not you please reset your password.,high,security
3,4,newsletter@blog.com,weekly tech newsletter,in this weeks edition learn about ai agents langgraph and more.,low,newsletter
4,5,friend123@gmail.com,coffee this weekend?,hey long time no see are you free this weekend for coffee?,medium,personal
5,6,spam@strangedomain.ru,you won 1000000,click here to claim your lottery now. do not share this with anyone.,high,spam
6,7,manager@company.com,project update required,please share the status update of your project before 5 pm today.,high,work
7,8,training@lms.com,reminder complete mandatory training,your mandatory security awareness training is due tomorrow.,medium,work

In [248]:
df['combined'] = (df['subject'] + " " + df['body']).str.strip()
df['combined'] = df['combined'].apply(clean)

In [249]:
pd.set_option('display.max_colwidth', None)
df[['id', 'sender', 'combined']]

,id,sender,combined
0,1,hr@company.com,offer letter please sign dear candidate congratulations please sign and upload your offer letter by today evening.
1,2,noreply@shopping.com,big billion sale is live flat 70 off on electronics. limited period offer. visit our store now.
2,3,alerts@mybank.com,unusual login attempt we detected a login attempt to your account from a new device. if this was not you please reset your password.
3,4,newsletter@blog.com,weekly tech newsletter in this weeks edition learn about ai agents langgraph and more.
4,5,friend123@gmail.com,coffee this weekend? hey long time no see are you free this weekend for coffee?
5,6,spam@strangedomain.ru,you won 1000000 click here to claim your lottery now. do not share this with anyone.
6,7,manager@company.com,project update required please share the status update of your project before 5 pm today.
7,8,training@lms.com,reminder complete mandatory training your mandatory security awareness training is due tomorrow.

In [250]:
df[df['combined'].str.contains("offer")]

,id,sender,subject,body,priority,label,combined
0,1,hr@company.com,offer letter please sign,dear candidate congratulations please sign and upload your offer letter by today evening.,high,important,offer letter please sign dear candidate congratulations please sign and upload your offer letter by today evening.
1,2,noreply@shopping.com,big billion sale is live,flat 70 off on electronics. limited period offer. visit our store now.,low,promotion,big billion sale is live flat 70 off on electronics. limited period offer. visit our store now.

In [251]:
df[df['priority'] == "high"]

,id,sender,subject,body,priority,label,combined
0,1,hr@company.com,offer letter please sign,dear candidate congratulations please sign and upload your offer letter by today evening.,high,important,offer letter please sign dear candidate congratulations please sign and upload your offer letter by today evening.
2,3,alerts@mybank.com,unusual login attempt,we detected a login attempt to your account from a new device. if this was not you please reset your password.,high,security,unusual login attempt we detected a login attempt to your account from a new device. if this was not you please reset your password.
5,6,spam@strangedomain.ru,you won 1000000,click here to claim your lottery now. do not share this with anyone.,high,spam,you won 1000000 click here to claim your lottery now. do not share this with anyone.
6,7,manager@company.com,project update required,please share the status update of your project before 5 pm today.,high,work,project update required please share the status update of your project before 5 pm today.

In [252]:
df[df['label'].isin(["important", "security"])]

,id,sender,subject,body,priority,label,combined
0,1,hr@company.com,offer letter please sign,dear candidate congratulations please sign and upload your offer letter by today evening.,high,important,offer letter please sign dear candidate congratulations please sign and upload your offer letter by today evening.
2,3,alerts@mybank.com,unusual login attempt,we detected a login attempt to your account from a new device. if this was not you please reset your password.,high,security,unusual login attempt we detected a login attempt to your account from a new device. if this was not you please reset your password.

In [253]:
df[df['combined'].str.contains("login", case=False)]

,id,sender,subject,body,priority,label,combined
2,3,alerts@mybank.com,unusual login attempt,we detected a login attempt to your account from a new device. if this was not you please reset your password.,high,security,unusual login attempt we detected a login attempt to your account from a new device. if this was not you please reset your password.

In [254]:
df[df['sender'] != "newsletter@blog.com"]

,id,sender,subject,body,priority,label,combined
0,1,hr@company.com,offer letter please sign,dear candidate congratulations please sign and upload your offer letter by today evening.,high,important,offer letter please sign dear candidate congratulations please sign and upload your offer letter by today evening.
1,2,noreply@shopping.com,big billion sale is live,flat 70 off on electronics. limited period offer. visit our store now.,low,promotion,big billion sale is live flat 70 off on electronics. limited period offer. visit our store now.
2,3,alerts@mybank.com,unusual login attempt,we detected a login attempt to your account from a new device. if this was not you please reset your password.,high,security,unusual login attempt we detected a login attempt to your account from a new device. if this was not you please reset your password.
4,5,friend123@gmail.com,coffee this weekend?,hey long time no see are you free this weekend for coffee?,medium,personal,coffee this weekend? hey long time no see are you free this weekend for coffee?
5,6,spam@strangedomain.ru,you won 1000000,click here to claim your lottery now. do not share this with anyone.,high,spam,you won 1000000 click here to claim your lottery now. do not share this with anyone.
6,7,manager@company.com,project update required,please share the status update of your project before 5 pm today.,high,work,project update required please share the status update of your project before 5 pm today.
7,8,training@lms.com,reminder complete mandatory training,your mandatory security awareness training is due tomorrow.,medium,work,reminder complete mandatory training your mandatory security awareness training is due tomorrow.

In [255]:
print(df.shape)

(8, 7)

In [256]:
df.isnull().sum()

id          0
sender      0
subject     0
body        0
priority    0
label       0
combined    0
dtype: int64

In [257]:
df['priority'].value_counts()

priority
high      4
low       2
medium    2
Name: count, dtype: int64

In [258]:
df['clean_text'] = df['body'].str.lower().str.replace(r'[^a-zA-Z\s]', '', regex=True) #pattern matching
df[['body','clean_text']].head()

,body,clean_text
0,dear candidate congratulations please sign and upload your offer letter by today evening.,dear candidate congratulations please sign and upload your offer letter by today evening
1,flat 70 off on electronics. limited period offer. visit our store now.,flat off on electronics limited period offer visit our store now
2,we detected a login attempt to your account from a new device. if this was not you please reset your password.,we detected a login attempt to your account from a new device if this was not you please reset your password
3,in this weeks edition learn about ai agents langgraph and more.,in this weeks edition learn about ai agents langgraph and more
4,hey long time no see are you free this weekend for coffee?,hey long time no see are you free this weekend for coffee

In [259]:
from collections import Counter

all_words = " ".join(df['clean_text']).split()
word_freq = Counter(all_words)

# Get only the most common word
top_word = word_freq.most_common(3)
print(top_word)

[('your', 6), ('this', 4), ('please', 3)]

In [260]:
from nltk.corpus import stopwords
stop = set(stopwords.words('english'))

df['clean_no_stop'] = df['clean_text'].apply(
    lambda x: " ".join([word for word in x.split() if word not in stop])
)

df.columns

Index(['id', 'sender', 'subject', 'body', 'priority', 'label', 'combined',
       'clean_text', 'clean_no_stop'],
      dtype='object')

In [261]:
import pandas as pd
df=pd.read_csv("../data/sample_emails.csv")

In [262]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\ARBIND KUMAR
[nltk_data]     ROY\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [263]:
df.head(3)

,id,sender,subject,body,priority,label
0,1,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign and upload your offer letter by today evening.",high,important
1,2,noreply@shopping.com,Big Billion Sale is Live,Flat 70% OFF on electronics. Limited period offer. Visit our store now.,low,promotion
2,3,alerts@mybank.com,Unusual Login Attempt,"We detected a login attempt to your account from a new device. If this was not you, please reset your password.",high,security

In [264]:
pd.DataFrame(word_freq.most_common(20), columns=["word", "count"])

               word  count
0              your      6
1              this      4
2            please      3
3               and      2
4             offer      2
5             today      2
6               now      2
7                 a      2
8                to      2
9               not      2
10              you      2
11            share      2
12             dear      1
13        candidate      1
14  congratulations      1
15             sign      1
16           upload      1
17           letter      1
18               by      1
19          evening      1