In [27]:
import pandas as pd
print("pandas")

pandas

In [28]:
import pandas as pd

df = pd.read_csv("../data/sample_emails.csv")
df.head()

,id,sender,subject,body,priority,label
0,1,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,important
1,2,noreply@shopping.com,Big Billion Sale is Live,Flat 70% OFF on electronics. Limited period of...,low,promotion
2,3,alerts@mybank.com,Unusual Login Attempt,We detected a login attempt to your account fr...,high,security
3,4,newsletter@blog.com,Weekly Tech Newsletter,"In this week's edition, learn about AI agents,...",low,newsletter
4,5,friend123@gmail.com,Coffee this weekend?,"Hey, long time no see! Are you free this weeke...",medium,personal

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        8 non-null      int64
 1   sender    8 non-null      object
 2   subject   8 non-null      object
 3   body      8 non-null      object
 4   priority  8 non-null      object
 5   label     8 non-null      object
dtypes: int64(1), object(5)
memory usage: 516.0+ bytes

In [30]:
df.describe(include="all")

,id,sender,subject,body,priority,label
count,8.00000,8,8,8,8,8
unique,NaN,8,8,8,3,7
top,NaN,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,work
freq,NaN,1,1,1,4,2
mean,4.50000,NaN,NaN,NaN,NaN,NaN
std,2.44949,NaN,NaN,NaN,NaN,NaN
min,1.00000,NaN,NaN,NaN,NaN,NaN
25%,2.75000,NaN,NaN,NaN,NaN,NaN
50%,4.50000,NaN,NaN,NaN,NaN,NaN
75%,6.25000,NaN,NaN,NaN,NaN,NaN
max,8.00000,NaN,NaN,NaN,NaN,NaN

In [31]:
df["label"].value_counts()

label
work          2
promotion     1
important     1
security      1
newsletter    1
personal      1
spam          1
Name: count, dtype: int64

In [32]:
df['subject'] = df['subject'].fillna('')
df['body'] = df['body'].fillna('')

In [34]:
df['subject'] = df['subject'].str.strip().str.lower()
df['body'] = df['body'].str.strip().str.lower()

In [35]:
#Create combined text column
df['text'] = df['subject'] + ' ' + df['body']
df[['text']]

                                                text
0  offer letter - please sign dear candidate, con...
1  big billion sale is live flat 70% off on elect...
2  unusual login attempt we detected a login atte...
3  weekly tech newsletter in this week's edition,...
4  coffee this weekend? hey, long time no see! ar...
5  you won $1,000,000!!! click here to claim your...
6  project update required please share the statu...
7  reminder: complete mandatory training your man...

In [36]:
# show all high priority emails
high_priority = df[df['priority'] == 'high']
high_priority

,id,sender,subject,body,priority,label,text
0,1,hr@company.com,offer letter - please sign,"dear candidate, congratulations! please sign a...",high,important,"offer letter - please sign dear candidate, con..."
2,3,alerts@mybank.com,unusual login attempt,we detected a login attempt to your account fr...,high,security,unusual login attempt we detected a login atte...
5,6,spam@strange-domain.ru,"you won $1,000,000!!!",click here to claim your lottery now. do not s...,high,spam,"you won $1,000,000!!! click here to claim your..."
6,7,manager@company.com,project update required,please share the status update of your project...,high,work,project update required please share the statu...

In [39]:
# security-related emails
security_emails = df[df['text'].str.contains('login|password|security', case=False, na=False)]
security_emails

,id,sender,subject,body,priority,label,text
2,3,alerts@mybank.com,unusual login attempt,we detected a login attempt to your account fr...,high,security,unusual login attempt we detected a login atte...
7,8,training@lms.com,reminder: complete mandatory training,your mandatory security awareness training is ...,medium,work,reminder: complete mandatory training your man...

In [41]:
# promotional/sale emails
promo_emails = df[df['text'].str.contains('sale|discount', case=False, na=False)]
promo_emails

,id,sender,subject,body,priority,label,text
1,2,noreply@shopping.com,big billion sale is live,flat 70% off on electronics. limited period of...,low,promotion,big billion sale is live flat 70% off on elect...