In [2]:
import pandas as pd
df = pd.read_csv("data/sample_emails.csv")
df.head()

,id,sender,subject,body,priority,label
0,1,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,important
1,2,noreply@shopping.com,Big Billion Sale is Live,Flat 70% OFF on electronics. Limited period of...,low,promotion
2,3,alerts@mybank.com,Unusual Login Attempt,We detected a login attempt to your account fr...,high,security
3,4,newsletter@blog.com,Weekly Tech Newsletter,"In this week's edition, learn about AI agents,...",low,newsletter
4,5,friend123@gmail.com,Coffee this weekend?,"Hey, long time no see! Are you free this weeke...",medium,personal

In [1]:
import os
os.chdir(r"C:\Users\Prana\OneDrive\Documents\GitHub\infosys-langgraph-email-assistant-group2")
print(os.getcwd())

C:\Users\Prana\OneDrive\Documents\GitHub\infosys-langgraph-email-assistant-group2

In [3]:
df.isnull().sum()

id          0
sender      0
subject     0
body        0
priority    0
label       0
dtype: int64

In [7]:
df["label"].value_counts()

label
work          2
promotion     1
important     1
security      1
newsletter    1
personal      1
spam          1
Name: count, dtype: int64

In [4]:
# Handle missing values
df['subject'] = df['subject'].fillna('').str.strip()
df['body'] = df['body'].fillna('').str.strip()

# Create cleaned lowercase versions
df['subject_clean'] = df['subject'].str.lower()
df['body_clean'] = df['body'].str.lower()

df.head()

,id,sender,subject,body,priority,label,subject_clean,body_clean
0,1,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,important,offer letter - please sign,"dear candidate, congratulations! please sign a..."
1,2,noreply@shopping.com,Big Billion Sale is Live,Flat 70% OFF on electronics. Limited period of...,low,promotion,big billion sale is live,flat 70% off on electronics. limited period of...
2,3,alerts@mybank.com,Unusual Login Attempt,We detected a login attempt to your account fr...,high,security,unusual login attempt,we detected a login attempt to your account fr...
3,4,newsletter@blog.com,Weekly Tech Newsletter,"In this week's edition, learn about AI agents,...",low,newsletter,weekly tech newsletter,"in this week's edition, learn about ai agents,..."
4,5,friend123@gmail.com,Coffee this weekend?,"Hey, long time no see! Are you free this weeke...",medium,personal,coffee this weekend?,"hey, long time no see! are you free this weeke..."

In [5]:
df.columns

Index(['id', 'sender', 'subject', 'body', 'priority', 'label', 'subject_clean',
       'body_clean'],
      dtype='object')

In [6]:
df['combined_text'] = df['subject'] + " " + df['body']
df[['subject', 'body', 'combined_text']].head()

,subject,body,combined_text
0,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...","Offer Letter - Please Sign Dear Candidate, Con..."
1,Big Billion Sale is Live,Flat 70% OFF on electronics. Limited period of...,Big Billion Sale is Live Flat 70% OFF on elect...
2,Unusual Login Attempt,We detected a login attempt to your account fr...,Unusual Login Attempt We detected a login atte...
3,Weekly Tech Newsletter,"In this week's edition, learn about AI agents,...","Weekly Tech Newsletter In this week's edition,..."
4,Coffee this weekend?,"Hey, long time no see! Are you free this weeke...","Coffee this weekend? Hey, long time no see! Ar..."

In [7]:
df[df['combined_text'].str.contains("offer", case=False)]

,id,sender,subject,body,priority,label,subject_clean,body_clean,combined_text
0,1,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,important,offer letter - please sign,"dear candidate, congratulations! please sign a...","Offer Letter - Please Sign Dear Candidate, Con..."
1,2,noreply@shopping.com,Big Billion Sale is Live,Flat 70% OFF on electronics. Limited period of...,low,promotion,big billion sale is live,flat 70% off on electronics. limited period of...,Big Billion Sale is Live Flat 70% OFF on elect...

In [8]:
df[df['priority'] == "high"]

,id,sender,subject,body,priority,label,subject_clean,body_clean,combined_text
0,1,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,important,offer letter - please sign,"dear candidate, congratulations! please sign a...","Offer Letter - Please Sign Dear Candidate, Con..."
2,3,alerts@mybank.com,Unusual Login Attempt,We detected a login attempt to your account fr...,high,security,unusual login attempt,we detected a login attempt to your account fr...,Unusual Login Attempt We detected a login atte...
5,6,spam@strange-domain.ru,"You won $1,000,000!!!",Click here to claim your lottery now. Do not s...,high,spam,"you won $1,000,000!!!",click here to claim your lottery now. do not s...,"You won $1,000,000!!! Click here to claim your..."
6,7,manager@company.com,Project Update Required,Please share the status update of your project...,high,work,project update required,please share the status update of your project...,Project Update Required Please share the statu...

In [9]:
df[df['label'] == "work"]

,id,sender,subject,body,priority,label,subject_clean,body_clean,combined_text
6,7,manager@company.com,Project Update Required,Please share the status update of your project...,high,work,project update required,please share the status update of your project...,Project Update Required Please share the statu...
7,8,training@lms.com,Reminder: Complete Mandatory Training,Your mandatory security awareness training is ...,medium,work,reminder: complete mandatory training,your mandatory security awareness training is ...,Reminder: Complete Mandatory Training Your man...

In [10]:
df[df['sender'].str.contains("hr", case=False)]

,id,sender,subject,body,priority,label,subject_clean,body_clean,combined_text
0,1,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,important,offer letter - please sign,"dear candidate, congratulations! please sign a...","Offer Letter - Please Sign Dear Candidate, Con..."

In [11]:
# Clean text
df['subject'] = df['subject'].fillna('').str.strip().str.lower()
df['body'] = df['body'].fillna('').str.strip().str.lower()

# Combine subject + body
df['combined_text'] = df['subject'] + " " + df['body']

In [12]:
def extract_priority(text):
    text = text.lower()

    if "high priority" in text or "urgent" in text or "immediately" in text:
        return "high"
    elif "medium priority" in text or "normal" in text:
        return "medium"
    elif "low priority" in text or "not urgent" in text:
        return "low"
    else:
        return "unknown"

In [13]:
# Clean priority column
df['priority'] = df['priority'].str.strip().str.lower()

df[['subject', 'priority']].head()

                      subject priority
0  offer letter - please sign     high
1    big billion sale is live      low
2       unusual login attempt     high
3      weekly tech newsletter      low
4        coffee this weekend?   medium

In [14]:
df.describe(include="all")

,id,sender,subject,body,priority,label,subject_clean,body_clean,combined_text
count,8.00000,8,8,8,8,8,8,8,8
unique,NaN,8,8,8,3,7,8,8,8
top,NaN,hr@company.com,offer letter - please sign,"dear candidate, congratulations! please sign a...",high,work,offer letter - please sign,"dear candidate, congratulations! please sign a...","offer letter - please sign dear candidate, con..."
freq,NaN,1,1,1,4,2,1,1,1
mean,4.50000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,2.44949,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,2.75000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,4.50000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,6.25000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,8.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df["label"].value_counts()

label
work          2
promotion     1
important     1
security      1
newsletter    1
personal      1
spam          1
Name: count, dtype: int64

In [16]:
df.shape
df.columns

Index(['id', 'sender', 'subject', 'body', 'priority', 'label', 'subject_clean',
       'body_clean', 'combined_text'],
      dtype='object')

In [17]:
df.isnull().sum()

id               0
sender           0
subject          0
body             0
priority         0
label            0
subject_clean    0
body_clean       0
combined_text    0
dtype: int64

In [22]:
df['clean_txt'] = df['body'].str.lower().str.replace('[^a-zA-Z ]','', regex=True)

In [25]:
df['priority'].value_counts()

priority
high      4
low       2
medium    2
Name: count, dtype: int64

In [26]:
print(df.shape)

(8, 10)

In [27]:
from collections import Counter
all_words = "".join(df['clean_txt'])
word_list = all_words.split()
word_freq = Counter(word_list)
word_freq.most_common(15)

[('your', 5),
 ('this', 4),
 ('please', 2),
 ('and', 2),
 ('offer', 2),
 ('a', 2),
 ('to', 2),
 ('not', 2),
 ('you', 2),
 ('share', 2),
 ('dear', 1),
 ('candidate', 1),
 ('congratulations', 1),
 ('sign', 1),
 ('upload', 1)]

In [31]:
pip install nltk

Requirement already satisfied: nltk in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (3.9.2)
Requirement already satisfied: click in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
filtered_words = [w for w in words if w not in stop_words]

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Prana\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

NameError: name 'words' is not defined

In [35]:
# 1. Get all text
all_text = " ".join(df['clean_txt'])
# 2. Split into words
words = all_text.split()
# 3. Import NLTK stopwords
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
# 4. Filter
filtered_words = [w for w in words if w not in stop_words]
filtered_words[:20]   # show first few

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Prana\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

['dear',
 'candidate',
 'congratulations',
 'please',
 'sign',
 'upload',
 'offer',
 'letter',
 'today',
 'evening',
 'flat',
 'electronics',
 'limited',
 'period',
 'offer',
 'visit',
 'store',
 'detected',
 'login',
 'attempt']