In [4]:
import pandas as pd
print("working")

working

In [5]:
df = pd.read_csv("../data/sample_emails.csv")
df.head()

,id,sender,subject,body,priority,label
0,1,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,important
1,2,noreply@shopping.com,Big Billion Sale is Live,Flat 70% OFF on electronics. Limited period of...,low,promotion
2,3,alerts@mybank.com,Unusual Login Attempt,We detected a login attempt to your account fr...,high,security
3,4,newsletter@blog.com,Weekly Tech Newsletter,"In this week's edition, learn about AI agents,...",low,newsletter
4,5,friend123@gmail.com,Coffee this weekend?,"Hey, long time no see! Are you free this weeke...",medium,personal

In [3]:
# Handle missing values
df['subject'] = df['subject'].fillna('').str.strip()
df['body'] = df['body'].fillna('').str.strip()

# Create cleaned lowercase versions
df['subject_clean'] = df['subject'].str.lower()
df['body_clean'] = df['body'].str.lower()

df.head()

,id,sender,subject,body,priority,label,subject_clean,body_clean
0,1,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,important,offer letter - please sign,"dear candidate, congratulations! please sign a..."
1,2,noreply@shopping.com,Big Billion Sale is Live,Flat 70% OFF on electronics. Limited period of...,low,promotion,big billion sale is live,flat 70% off on electronics. limited period of...
2,3,alerts@mybank.com,Unusual Login Attempt,We detected a login attempt to your account fr...,high,security,unusual login attempt,we detected a login attempt to your account fr...
3,4,newsletter@blog.com,Weekly Tech Newsletter,"In this week's edition, learn about AI agents,...",low,newsletter,weekly tech newsletter,"in this week's edition, learn about ai agents,..."
4,5,friend123@gmail.com,Coffee this weekend?,"Hey, long time no see! Are you free this weeke...",medium,personal,coffee this weekend?,"hey, long time no see! are you free this weeke..."

In [4]:
df.columns

Index(['id', 'sender', 'subject', 'body', 'priority', 'label', 'subject_clean',
       'body_clean'],
      dtype='object')

In [5]:
df['combined_text'] = df['subject'] + " " + df['body']
df[['subject', 'body', 'combined_text']].head()

,subject,body,combined_text
0,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...","Offer Letter - Please Sign Dear Candidate, Con..."
1,Big Billion Sale is Live,Flat 70% OFF on electronics. Limited period of...,Big Billion Sale is Live Flat 70% OFF on elect...
2,Unusual Login Attempt,We detected a login attempt to your account fr...,Unusual Login Attempt We detected a login atte...
3,Weekly Tech Newsletter,"In this week's edition, learn about AI agents,...","Weekly Tech Newsletter In this week's edition,..."
4,Coffee this weekend?,"Hey, long time no see! Are you free this weeke...","Coffee this weekend? Hey, long time no see! Ar..."

In [6]:
df[df['combined_text'].str.contains("offer", case=False)]

,id,sender,subject,body,priority,label,subject_clean,body_clean,combined_text
0,1,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,important,offer letter - please sign,"dear candidate, congratulations! please sign a...","Offer Letter - Please Sign Dear Candidate, Con..."
1,2,noreply@shopping.com,Big Billion Sale is Live,Flat 70% OFF on electronics. Limited period of...,low,promotion,big billion sale is live,flat 70% off on electronics. limited period of...,Big Billion Sale is Live Flat 70% OFF on elect...

In [7]:
df[df['priority'] == "high"]

,id,sender,subject,body,priority,label,subject_clean,body_clean,combined_text
0,1,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,important,offer letter - please sign,"dear candidate, congratulations! please sign a...","Offer Letter - Please Sign Dear Candidate, Con..."
2,3,alerts@mybank.com,Unusual Login Attempt,We detected a login attempt to your account fr...,high,security,unusual login attempt,we detected a login attempt to your account fr...,Unusual Login Attempt We detected a login atte...
5,6,spam@strange-domain.ru,"You won $1,000,000!!!",Click here to claim your lottery now. Do not s...,high,spam,"you won $1,000,000!!!",click here to claim your lottery now. do not s...,"You won $1,000,000!!! Click here to claim your..."
6,7,manager@company.com,Project Update Required,Please share the status update of your project...,high,work,project update required,please share the status update of your project...,Project Update Required Please share the statu...

In [8]:
df[df['label'] == "work"]

,id,sender,subject,body,priority,label,subject_clean,body_clean,combined_text
6,7,manager@company.com,Project Update Required,Please share the status update of your project...,high,work,project update required,please share the status update of your project...,Project Update Required Please share the statu...
7,8,training@lms.com,Reminder: Complete Mandatory Training,Your mandatory security awareness training is ...,medium,work,reminder: complete mandatory training,your mandatory security awareness training is ...,Reminder: Complete Mandatory Training Your man...

In [9]:
df[df['sender'].str.contains("hr", case=False)]

,id,sender,subject,body,priority,label,subject_clean,body_clean,combined_text
0,1,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,important,offer letter - please sign,"dear candidate, congratulations! please sign a...","Offer Letter - Please Sign Dear Candidate, Con..."

In [36]:
# Clean text
df['subject'] = df['subject'].fillna('').str.strip().str.lower()
df['body'] = df['body'].fillna('').str.strip().str.lower()

# Combine subject + body
df['combined_text'] = df['subject'] + " " + df['body']

In [11]:
def extract_priority(text):
    text = text.lower()

    if "high priority" in text or "urgent" in text or "immediately" in text:
        return "high"
    elif "medium priority" in text or "normal" in text:
        return "medium"
    elif "low priority" in text or "not urgent" in text:
        return "low"
    else:
        return "unknown"

In [9]:
# Clean priority column
df['priority'] = df['priority'].str.strip().str.lower()

df[['subject', 'priority']].head()

                      subject priority
0  Offer Letter - Please Sign     high
1    Big Billion Sale is Live      low
2       Unusual Login Attempt     high
3      Weekly Tech Newsletter      low
4        Coffee this weekend?   medium

In [13]:
df.describe(include="all")

,id,sender,subject,body,priority,label,subject_clean,body_clean,combined_text
count,8.00000,8,8,8,8,8,8,8,8
unique,NaN,8,8,8,3,7,8,8,8
top,NaN,hr@company.com,offer letter - please sign,"dear candidate, congratulations! please sign a...",high,work,offer letter - please sign,"dear candidate, congratulations! please sign a...","offer letter - please sign dear candidate, con..."
freq,NaN,1,1,1,4,2,1,1,1
mean,4.50000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,2.44949,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,2.75000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,4.50000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,6.25000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,8.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df["label"].value_counts()

label
work          2
promotion     1
important     1
security      1
newsletter    1
personal      1
spam          1
Name: count, dtype: int64

In [6]:
df.shape
df.columns

Index(['id', 'sender', 'subject', 'body', 'priority', 'label',
       'combined_text'],
      dtype='object')

In [ ]:
df.isnull().sum()

id               0
sender           0
subject          0
body             0
priority         0
label            0
subject_clean    0
body_clean       0
combined_text    0
dtype: int64

In [ ]:
df['clean_txt']=df['body'].str.lower().str.replace('[^a-zA-Z]','',regex=True)
df[['body','clean_txt']].head()

,body,clean_txt
0,"dear candidate, congratulations! please sign a...",dearcandidatecongratulationspleasesignanduploa...
1,flat 70% off on electronics. limited period of...,flatoffonelectronicslimitedperiodoffervisitour...
2,we detected a login attempt to your account fr...,wedetectedaloginattempttoyouraccountfromanewde...
3,"in this week's edition, learn about ai agents,...",inthisweekseditionlearnaboutaiagentslanggrapha...
4,"hey, long time no see! are you free this weeke...",heylongtimenoseeareyoufreethisweekendforcoffee

In [ ]:
df['priority'].value_counts()

priority
high      4
low       2
medium    2
Name: count, dtype: int64

In [5]:
print(df.shape)

(8, 7)

In [22]:
from collections import Counter

all_words = ' '.join(df['clean_txt']).split()
word_freq = Counter(all_words)
word_freq.most_common(10)

[('dearcandidatecongratulationspleasesignanduploadyourofferletterbytodayevening',
  1),
 ('flatoffonelectronicslimitedperiodoffervisitourstorenow', 1),
 ('wedetectedaloginattempttoyouraccountfromanewdeviceifthiswasnotyoupleaseresetyourpassword',
  1),
 ('inthisweekseditionlearnaboutaiagentslanggraphandmore', 1),
 ('heylongtimenoseeareyoufreethisweekendforcoffee', 1),
 ('clickheretoclaimyourlotterynowdonotsharethiswithanyone', 1),
 ('pleasesharethestatusupdateofyourprojectbeforepmtoday', 1),
 ('yourmandatorysecurityawarenesstrainingisduetomorrow', 1)]

In [12]:
df.columns

Index(['id', 'sender', 'subject', 'body', 'priority', 'label'], dtype='object')

In [13]:
df['clean_txt']=df['body'].str.lower().str.replace('[^a-zA-Z]','',regex=True)

In [15]:
all_words = ' '.join(df['clean_txt']).split()

In [21]:
len(all_words)

8

In [28]:
import nltk #natural language toolkit
nltk.download('stopwords')
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))
filtered_words = [word for word in all_words if word not in stop_words]
filtered_words

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\psinc\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

['dearcandidatecongratulationspleasesignanduploadyourofferletterbytodayevening',
 'flatoffonelectronicslimitedperiodoffervisitourstorenow',
 'wedetectedaloginattempttoyouraccountfromanewdeviceifthiswasnotyoupleaseresetyourpassword',
 'inthisweekseditionlearnaboutaiagentslanggraphandmore',
 'heylongtimenoseeareyoufreethisweekendforcoffee',
 'clickheretoclaimyourlotterynowdonotsharethiswithanyone',
 'pleasesharethestatusupdateofyourprojectbeforepmtoday',
 'yourmandatorysecurityawarenesstrainingisduetomorrow']

In [24]:
pip install nltk

Collecting nltk
  Downloading nltk-3.9.2-py3-none-any.whl (1.5 MB)
     ---------------------------------------- 1.5/1.5 MB 395.9 kB/s eta 0:00:00
Collecting joblib
  Downloading joblib-1.5.2-py3-none-any.whl (308 kB)
     ------------------------------------ 308.4/308.4 kB 443.7 kB/s eta 0:00:00
Collecting tqdm
  Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
     -------------------------------------- 78.5/78.5 kB 256.8 kB/s eta 0:00:00
Collecting click
  Downloading click-8.3.1-py3-none-any.whl (108 kB)
     ------------------------------------- 108.3/108.3 kB 44.8 kB/s eta 0:00:00
Collecting regex>=2021.8.3
  Downloading regex-2025.11.3-cp310-cp310-win_amd64.whl (277 kB)
     ------------------------------------ 277.7/277.7 kB 146.3 kB/s eta 0:00:00
Requirement already satisfied: colorama in c:\users\psinc\appdata\roaming\python\python310\site-packages (from click->nltk) (0.4.6)
Installing collected packages: tqdm, regex, joblib, click, nltk
Successfully installed click-8.3.1 joblib-1.5.2 nltk-3.9.2 regex-2025.11.3 tqdm-4.67.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.2.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [29]:
pip install nltk pandas

Requirement already satisfied: nltk in c:\users\psinc\appdata\local\programs\python\python310\lib\site-packages (3.9.2)
Requirement already satisfied: pandas in c:\users\psinc\appdata\local\programs\python\python310\lib\site-packages (2.3.3)
Requirement already satisfied: click in c:\users\psinc\appdata\local\programs\python\python310\lib\site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in c:\users\psinc\appdata\local\programs\python\python310\lib\site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\psinc\appdata\local\programs\python\python310\lib\site-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in c:\users\psinc\appdata\local\programs\python\python310\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: numpy>=1.22.4 in c:\users\psinc\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\psinc\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\psinc\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\psinc\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\psinc\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: colorama in c:\users\psinc\appdata\roaming\python\python310\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [30]:
import pandas as pd
import nltk
from nltk.corpus import stopwords
from collections import Counter

In [31]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\psinc\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [34]:
df = pd.read_csv(r'..\data\sample_emails.csv')
df.head()

,id,sender,subject,body,priority,label
0,1,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,important
1,2,noreply@shopping.com,Big Billion Sale is Live,Flat 70% OFF on electronics. Limited period of...,low,promotion
2,3,alerts@mybank.com,Unusual Login Attempt,We detected a login attempt to your account fr...,high,security
3,4,newsletter@blog.com,Weekly Tech Newsletter,"In this week's edition, learn about AI agents,...",low,newsletter
4,5,friend123@gmail.com,Coffee this weekend?,"Hey, long time no see! Are you free this weeke...",medium,personal

In [39]:
df['text'] = df['subject'].fillna('') + ' ' + df['body'].fillna('')
df['clean_text'] = df['text'].str.lower().str.strip()

In [41]:
stop_words = set(stopwords.words('english'))

df['clean_text'] = df['clean_text'].apply(
    lambda x: ' '.join([word for word in x.split() if word not in stop_words])
)

In [42]:
df[['text', 'clean_text']].head(3)

,text,clean_text
0,"offer letter - please sign dear candidate, con...","offer letter - please sign dear candidate, con..."
1,big billion sale is live flat 70% off on elect...,big billion sale live flat 70% electronics. li...
2,unusual login attempt we detected a login atte...,unusual login attempt detected login attempt a...

In [43]:
all_words = ' '.join(df['clean_text']).split()
word_freq = Counter(all_words)

word_freq.most_common(10)

[('please', 4),
 ('offer', 2),
 ('letter', 2),
 ('sign', 2),
 ('now.', 2),
 ('login', 2),
 ('attempt', 2),
 ('share', 2),
 ('project', 2),
 ('update', 2)]