In [2]:
import pandas as pd
print(pd.__version__)

2.3.0

In [3]:
import pandas as pd
df=pd.read_csv("../data/sample_emails.csv")
df.head()

,id,sender,subject,body,priority,label
0,1,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,important
1,2,noreply@shopping.com,Big Billion Sale is Live,Flat 70% OFF on electronics. Limited period of...,low,promotion
2,3,alerts@mybank.com,Unusual Login Attempt,We detected a login attempt to your account fr...,high,security
3,4,newsletter@blog.com,Weekly Tech Newsletter,"In this week's edition, learn about AI agents,...",low,newsletter
4,5,friend123@gmail.com,Coffee this weekend?,"Hey, long time no see! Are you free this weeke...",medium,personal

In [4]:
df.columns

Index(['id', 'sender', 'subject', 'body', 'priority', 'label'], dtype='object')

In [5]:
df.info

<bound method DataFrame.info of    id                  sender                                subject  \
0   1          hr@company.com             Offer Letter - Please Sign
1   2    noreply@shopping.com               Big Billion Sale is Live
2   3       alerts@mybank.com                  Unusual Login Attempt
3   4     newsletter@blog.com                 Weekly Tech Newsletter
4   5     friend123@gmail.com                   Coffee this weekend?
5   6  spam@strange-domain.ru                  You won $1,000,000!!!
6   7     manager@company.com                Project Update Required
7   8        training@lms.com  Reminder: Complete Mandatory Training

                                                body priority       label
0  Dear Candidate, Congratulations! Please sign a...     high   important
1  Flat 70% OFF on electronics. Limited period of...      low   promotion
2  We detected a login attempt to your account fr...     high    security
3  In this week's edition, learn about AI agents,...      low  newsletter
4  Hey, long time no see! Are you free this weeke...   medium    personal
5  Click here to claim your lottery now. Do not s...     high        spam
6  Please share the status update of your project...     high        work
7  Your mandatory security awareness training is ...   medium        work  >

In [6]:
df.describe(include="all")

,id,sender,subject,body,priority,label
count,8.00000,8,8,8,8,8
unique,NaN,8,8,8,3,7
top,NaN,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,work
freq,NaN,1,1,1,4,2
mean,4.50000,NaN,NaN,NaN,NaN,NaN
std,2.44949,NaN,NaN,NaN,NaN,NaN
min,1.00000,NaN,NaN,NaN,NaN,NaN
25%,2.75000,NaN,NaN,NaN,NaN,NaN
50%,4.50000,NaN,NaN,NaN,NaN,NaN
75%,6.25000,NaN,NaN,NaN,NaN,NaN
max,8.00000,NaN,NaN,NaN,NaN,NaN

In [7]:
df["label"].value_counts()

label
work          2
promotion     1
important     1
security      1
newsletter    1
personal      1
spam          1
Name: count, dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        8 non-null      int64
 1   sender    8 non-null      object
 2   subject   8 non-null      object
 3   body      8 non-null      object
 4   priority  8 non-null      object
 5   label     8 non-null      object
dtypes: int64(1), object(5)
memory usage: 512.0+ bytes

In [9]:
df.describe(include="all")

,id,sender,subject,body,priority,label
count,8.00000,8,8,8,8,8
unique,NaN,8,8,8,3,7
top,NaN,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,work
freq,NaN,1,1,1,4,2
mean,4.50000,NaN,NaN,NaN,NaN,NaN
std,2.44949,NaN,NaN,NaN,NaN,NaN
min,1.00000,NaN,NaN,NaN,NaN,NaN
25%,2.75000,NaN,NaN,NaN,NaN,NaN
50%,4.50000,NaN,NaN,NaN,NaN,NaN
75%,6.25000,NaN,NaN,NaN,NaN,NaN
max,8.00000,NaN,NaN,NaN,NaN,NaN

In [11]:
df["label"].value_counts()

label
work          2
promotion     1
important     1
security      1
newsletter    1
personal      1
spam          1
Name: count, dtype: int64

In [12]:
important_cols = df[["subject", "sender"]]
important_cols.head()

                      subject                sender
0  Offer Letter - Please Sign        hr@company.com
1    Big Billion Sale is Live  noreply@shopping.com
2       Unusual Login Attempt     alerts@mybank.com
3      Weekly Tech Newsletter   newsletter@blog.com
4        Coffee this weekend?   friend123@gmail.com

In [13]:
#select specific columns from a dataframe
important_cols = df[["subject", "sender"]]
important_cols.head()

                      subject                sender
0  Offer Letter - Please Sign        hr@company.com
1    Big Billion Sale is Live  noreply@shopping.com
2       Unusual Login Attempt     alerts@mybank.com
3      Weekly Tech Newsletter   newsletter@blog.com
4        Coffee this weekend?   friend123@gmail.com

In [15]:

df.columns

Index(['id', 'sender', 'subject', 'body', 'priority', 'label'], dtype='object')

In [16]:
df['label'].value_counts()

label
work          2
promotion     1
important     1
security      1
newsletter    1
personal      1
spam          1
Name: count, dtype: int64

In [17]:
#find and display only the messages that contain the word "offer
offer_only = df[df['combined'].str.contains("offer")]
print(df)
print("\nOffer Messages:")
print(offer_only)

   id                  sender                                subject  \
0   1          hr@company.com             offer letter - please sign
1   2    noreply@shopping.com               big billion sale is live
2   3       alerts@mybank.com                  unusual login attempt
3   4     newsletter@blog.com                 weekly tech newsletter
4   5     friend123@gmail.com                   coffee this weekend?
5   6  spam@strange-domain.ru                  you won $1,000,000!!!
6   7     manager@company.com                project update required
7   8        training@lms.com  reminder: complete mandatory training

                                                body priority       label
0  dear candidate, congratulations! please sign a...     high   important
1  flat 70% off on electronics. limited period of...      low   promotion
2  we detected a login attempt to your account fr...     high    security
3  in this week's edition, learn about ai agents,...      low  newsletter
4  hey, long time no see! are you free this weeke...   medium    personal
5  click here to claim your lottery now. do not s...     high        spam
6  please share the status update of your project...     high        work
7  your mandatory security awareness training is ...   medium        work

In [18]:
df['combined'] = df['subject'] + " " + df['body']
print(df)

   id                  sender                                subject  \
0   1          hr@company.com             offer letter - please sign
1   2    noreply@shopping.com               big billion sale is live
2   3       alerts@mybank.com                  unusual login attempt
3   4     newsletter@blog.com                 weekly tech newsletter
4   5     friend123@gmail.com                   coffee this weekend?
5   6  spam@strange-domain.ru                  you won $1,000,000!!!
6   7     manager@company.com                project update required
7   8        training@lms.com  reminder: complete mandatory training

                                                body priority       label  \
0  dear candidate, congratulations! please sign a...     high   important
1  flat 70% off on electronics. limited period of...      low   promotion
2  we detected a login attempt to your account fr...     high    security
3  in this week's edition, learn about ai agents,...      low  newsletter
4  hey, long time no see! are you free this weeke...   medium    personal
5  click here to claim your lottery now. do not s...     high        spam
6  please share the status update of your project...     high        work
7  your mandatory security awareness training is ...   medium        work

                                            combined
0  offer letter - please sign dear candidate, con...
1  big billion sale is live flat 70% off on elect...
2  unusual login attempt we detected a login atte...
3  weekly tech newsletter in this week's edition,...
4  coffee this weekend? hey, long time no see! ar...
5  you won $1,000,000!!! click here to claim your...
6  project update required please share the statu...
7  reminder: complete mandatory training your man...

In [19]:
offer_only = df[df['combined'].str.contains("offer")]
print(df)
print("\nOffer Messages:")
print(offer_only)

   id                  sender                                subject  \
0   1          hr@company.com             offer letter - please sign
1   2    noreply@shopping.com               big billion sale is live
2   3       alerts@mybank.com                  unusual login attempt
3   4     newsletter@blog.com                 weekly tech newsletter
4   5     friend123@gmail.com                   coffee this weekend?
5   6  spam@strange-domain.ru                  you won $1,000,000!!!
6   7     manager@company.com                project update required
7   8        training@lms.com  reminder: complete mandatory training

                                                body priority       label  \
0  dear candidate, congratulations! please sign a...     high   important
1  flat 70% off on electronics. limited period of...      low   promotion
2  we detected a login attempt to your account fr...     high    security
3  in this week's edition, learn about ai agents,...      low  newsletter
4  hey, long time no see! are you free this weeke...   medium    personal
5  click here to claim your lottery now. do not s...     high        spam
6  please share the status update of your project...     high        work
7  your mandatory security awareness training is ...   medium        work

                                            combined
0  offer letter - please sign dear candidate, con...
1  big billion sale is live flat 70% off on elect...
2  unusual login attempt we detected a login atte...
3  weekly tech newsletter in this week's edition,...
4  coffee this weekend? hey, long time no see! ar...
5  you won $1,000,000!!! click here to claim your...
6  project update required please share the statu...
7  reminder: complete mandatory training your man...

Offer Messages:
   id                sender                     subject  \
0   1        hr@company.com  offer letter - please sign
1   2  noreply@shopping.com    big billion sale is live

                                                body priority      label  \
0  dear candidate, congratulations! please sign a...     high  important
1  flat 70% off on electronics. limited period of...      low  promotion

                                            combined
0  offer letter - please sign dear candidate, con...
1  big billion sale is live flat 70% off on elect...

In [20]:
important_only = df[df['label'].str.contains("important")]
print(important_only)

   id          sender                     subject  \
0   1  hr@company.com  offer letter - please sign

                                                body priority      label  \
0  dear candidate, congratulations! please sign a...     high  important

                                            combined
0  offer letter - please sign dear candidate, con...

In [21]:
df.shape

(8, 7)

In [22]:
df.isnull().sum()

id          0
sender      0
subject     0
body        0
priority    0
label       0
combined    0
dtype: int64

In [23]:

df['subject'][0]

'offer letter - please sign'

In [24]:

df['subject'][0]

'offer letter - please sign'

In [25]:

df['clean_txt']=df['body'].str.lower().str.replace('[^a-zA-Z]','',regex=True)
df[['body','clean_txt']].head()

,body,clean_txt
0,"dear candidate, congratulations! please sign a...",dearcandidatecongratulationspleasesignanduploa...
1,flat 70% off on electronics. limited period of...,flatoffonelectronicslimitedperiodoffervisitour...
2,we detected a login attempt to your account fr...,wedetectedaloginattempttoyouraccountfromanewde...
3,"in this week's edition, learn about ai agents,...",inthisweekseditionlearnaboutaiagentslanggrapha...
4,"hey, long time no see! are you free this weeke...",heylongtimenoseeareyoufreethisweekendforcoffee

In [26]:
from collections import Counter
all_words ="".join(df['clean_txt']).split()
word_freq = Counter(all_words)
word_freq.most_common(3)

[('dearcandidatecongratulationspleasesignanduploadyourofferletterbytodayeveningflatoffonelectronicslimitedperiodoffervisitourstorenowwedetectedaloginattempttoyouraccountfromanewdeviceifthiswasnotyoupleaseresetyourpasswordinthisweekseditionlearnaboutaiagentslanggraphandmoreheylongtimenoseeareyoufreethisweekendforcoffeeclickheretoclaimyourlotterynowdonotsharethiswithanyonepleasesharethestatusupdateofyourprojectbeforepmtodayyourmandatorysecurityawarenesstrainingisduetomorrow',
  1)]

In [27]:
all_words_text=" ".join(df['clean_txt']).split()
words=all_words_text

In [31]:

len(words)

8

In [33]:
pip install nltk

Collecting nltk
  Downloading nltk-3.9.2-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: click in c:\users\theer\appdata\local\programs\python\python311\lib\site-packages (from nltk) (8.1.8)
Collecting joblib (from nltk)
  Downloading joblib-1.5.2-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: regex>=2021.8.3 in c:\users\theer\appdata\local\programs\python\python311\lib\site-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in c:\users\theer\appdata\local\programs\python\python311\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\theer\appdata\local\programs\python\python311\lib\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.9.2-py3-none-any.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ------------- -------------------------- 0.5/1.5 MB 1.9 MB/s eta 0:00:01
   --------------------------- ------------ 1.0/1.5 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 2.4 MB/s eta 0:00:00
Downloading joblib-1.5.2-py3-none-any.whl (308 kB)
Installing collected packages: joblib, nltk

   ---------------------------------------- 0/2 [joblib]
   ---------------------------------------- 0/2 [joblib]
   ---------------------------------------- 0/2 [joblib]
   ---------------------------------------- 0/2 [joblib]
   ---------------------------------------- 0/2 [joblib]
   ---------------------------------------- 0/2 [joblib]
   ---------------------------------------- 0/2 [joblib]
   ---------------------------------------- 0/2 [joblib]
   ---------------------------------------- 0/2 [joblib]
   ---------------------------------------- 0/2 [joblib]
   ---------------------------------------- 0/2 [joblib]
   ---------------------------------------- 0/2 [joblib]
   ---------------------------------------- 0/2 [joblib]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   ---------------------------------------- 2/2 [nltk]

Successfully installed joblib-1.5.2 nltk-3.9.2
Note: you may need to restart the kernel to use updated packages.

  WARNING: The script nltk.exe is installed in 'c:\Users\theer\AppData\Local\Programs\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [34]:
import nltk 
nltk.download('stopwords')
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))
filtered_words=[w for w in words if w not in stop_words]

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\theer\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [35]:
import re

df['clean_text'] = (
    df['body']
    .str.lower()                              
    .str.replace(r'[^a-z\s]', '', regex=True) 
    .str.replace(r'\s+', ' ', regex=True)     
    .str.strip()
)
print(df['clean_text'])

0    dear candidate congratulations please sign and...
1    flat off on electronics limited period offer v...
2    we detected a login attempt to your account fr...
3    in this weeks edition learn about ai agents la...
4    hey long time no see are you free this weekend...
5    click here to claim your lottery now do not sh...
6    please share the status update of your project...
7    your mandatory security awareness training is ...
Name: clean_text, dtype: object

In [36]:
import nltk

nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\theer\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\theer\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [37]:
from nltk.tokenize import wordpunct_tokenize

def remove_stopwords(text):
    if not isinstance(text, str):
        return ""
    words = wordpunct_tokenize(text.lower())
    return " ".join([w for w in words if w.isalpha() and w not in stop_words])

df['clean_text'] = df['body'].fillna("").apply(remove_stopwords)

In [38]:
print(df['clean_text'])

0    dear candidate congratulations please sign upl...
1    flat electronics limited period offer visit store
2    detected login attempt account new device plea...
3               week edition learn ai agents langgraph
4                hey long time see free weekend coffee
5                     click claim lottery share anyone
6          please share status update project pm today
7    mandatory security awareness training due tomo...
Name: clean_text, dtype: object

In [39]:

df['clean_text'].head(3)

0    dear candidate congratulations please sign upl...
1    flat electronics limited period offer visit store
2    detected login attempt account new device plea...
Name: clean_text, dtype: object

In [41]:
from collections import Counter

# Combine 
all_words = " ".join(df['clean_text']).split()

# Count word frequency
word_freq = Counter(all_words)

# Convert to DataFrame
word_freq_df = (
    pd.DataFrame(word_freq.items(), columns=['Word', 'Frequency'])
    .sort_values(by='Frequency', ascending=False)
)

# Show top 10 words
word_freq_df.head(10)

               Word  Frequency
3            please          3
6             offer          2
8             today          2
40            share          2
2   congratulations          1
1         candidate          1
5            upload          1
4              sign          1
7            letter          1
9           evening          1

In [42]:
from collections import Counter
all_words = " ".join(df['clean_text']).split()
word_freq = Counter(all_words)
word_freq_df = (pd.DataFrame(word_freq.items(), columns=['Word', 'Frequency'])
                .sort_values(by='Frequency', ascending=False))
word_freq_df.head()

               Word  Frequency
3            please          3
6             offer          2
8             today          2
40            share          2
2   congratulations          1

In [43]:
# 3. Remove stopwords using NLTK
stop_words = set(stopwords.words("english"))

def remove_stopwords(text: str) -> str:
    words = text.split()                      # simple tokenization
    filtered = [w for w in words if w not in stop_words]
    return " ".join(filtered)

df["clean_no_stop"] = df["clean_text"].apply(remove_stopwords)

# 4. Show first 3 rows
print("First 3 rows:")
print(df.head(3))

First 3 rows:
   id                sender                     subject  \
0   1        hr@company.com  offer letter - please sign
1   2  noreply@shopping.com    big billion sale is live
2   3     alerts@mybank.com       unusual login attempt

                                                body priority      label  \
0  dear candidate, congratulations! please sign a...     high  important
1  flat 70% off on electronics. limited period of...      low  promotion
2  we detected a login attempt to your account fr...     high   security

                                            combined  \
0  offer letter - please sign dear candidate, con...
1  big billion sale is live flat 70% off on elect...
2  unusual login attempt we detected a login atte...

                                           clean_txt  \
0  dearcandidatecongratulationspleasesignanduploa...
1  flatoffonelectronicslimitedperiodoffervisitour...
2  wedetectedaloginattempttoyouraccountfromanewde...

                                          clean_text  \
0  dear candidate congratulations please sign upl...
1  flat electronics limited period offer visit store
2  detected login attempt account new device plea...

                                       clean_no_stop
0  dear candidate congratulations please sign upl...
1  flat electronics limited period offer visit store
2  detected login attempt account new device plea...

In [45]:
# 5. Analyze word frequency (using clean text without stopwords)
all_words = " ".join(df["clean_no_stop"]).split()
word_freq = Counter(all_words)
print("Top 10 frequent words:\n", word_freq.most_common(10))

Top 10 frequent words:
 [('please', 3), ('offer', 2), ('today', 2), ('share', 2), ('dear', 1), ('candidate', 1), ('congratulations', 1), ('sign', 1), ('upload', 1), ('letter', 1)]

In [47]:
#spam key word detection
spam_keywords = ["offer", "free", "win", "discount", "cashback", "prize", "limited"]

def check_spam(text):
    text = text.lower()
    return any(keyword in text for keyword in spam_keywords)

df['spam_detected'] = df['body'].apply(check_spam)
df[['subject','spam_detected']].head()

                      subject  spam_detected
0  offer letter - please sign           True
1    big billion sale is live           True
2       unusual login attempt          False
3      weekly tech newsletter          False
4        coffee this weekend?           True

In [48]:
#stemming
from nltk.stem import PorterStemmer

ps = PorterStemmer()

def stem_text(text):
    if not isinstance(text, str):
        return ""
    # we can stem from clean_text 
    words = text.split()
    stemmed_words = [ps.stem(w) for w in words]
    return " ".join(stemmed_words)

df["stemmed"] = df["clean_text"].apply(stem_text)

print("\nSample Stemming:")
print(df[["clean_text", "stemmed"]].head())

Sample Stemming:
                                          clean_text  \
0  dear candidate congratulations please sign upl...
1  flat electronics limited period offer visit store
2  detected login attempt account new device plea...
3             week edition learn ai agents langgraph
4              hey long time see free weekend coffee

                                             stemmed
0  dear candid congratul pleas sign upload offer ...
1       flat electron limit period offer visit store
2  detect login attempt account new devic pleas r...
3                 week edit learn ai agent langgraph
4               hey long time see free weekend coffe