In [6]:
import pandas as pd

df = pd.read_csv("../data/sample_emails.csv")
df.head()

,id,sender,subject,body,priority,label
0,1,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,important
1,2,noreply@shopping.com,Big Billion Sale is Live,Flat 70% OFF on electronics. Limited period of...,low,promotion
2,3,alerts@mybank.com,Unusual Login Attempt,We detected a login attempt to your account fr...,high,security
3,4,newsletter@blog.com,Weekly Tech Newsletter,"In this week's edition, learn about AI agents,...",low,newsletter
4,5,friend123@gmail.com,Coffee this weekend?,"Hey, long time no see! Are you free this weeke...",medium,personal

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        8 non-null      int64
 1   sender    8 non-null      object
 2   subject   8 non-null      object
 3   body      8 non-null      object
 4   priority  8 non-null      object
 5   label     8 non-null      object
dtypes: int64(1), object(5)
memory usage: 516.0+ bytes

In [8]:
df.describe(include="all")

,id,sender,subject,body,priority,label
count,8.00000,8,8,8,8,8
unique,NaN,8,8,8,3,7
top,NaN,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,work
freq,NaN,1,1,1,4,2
mean,4.50000,NaN,NaN,NaN,NaN,NaN
std,2.44949,NaN,NaN,NaN,NaN,NaN
min,1.00000,NaN,NaN,NaN,NaN,NaN
25%,2.75000,NaN,NaN,NaN,NaN,NaN
50%,4.50000,NaN,NaN,NaN,NaN,NaN
75%,6.25000,NaN,NaN,NaN,NaN,NaN
max,8.00000,NaN,NaN,NaN,NaN,NaN

In [9]:
df["label"].value_counts()

label
work          2
promotion     1
important     1
security      1
newsletter    1
personal      1
spam          1
Name: count, dtype: int64

In [10]:
df['subject'] = df['subject'].fillna('')
df['body'] = df['body'].fillna('')

In [11]:
#Create combined text column
df['text'] = df['subject'] + ' ' + df['body']
df[['text']]

                                                text
0  Offer Letter - Please Sign Dear Candidate, Con...
1  Big Billion Sale is Live Flat 70% OFF on elect...
2  Unusual Login Attempt We detected a login atte...
3  Weekly Tech Newsletter In this week's edition,...
4  Coffee this weekend? Hey, long time no see! Ar...
5  You won $1,000,000!!! Click here to claim your...
6  Project Update Required Please share the statu...
7  Reminder: Complete Mandatory Training Your man...

In [12]:
# show all high priority emails
high_priority = df[df['priority'] == 'high']
high_priority

,id,sender,subject,body,priority,label,text
0,1,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,important,"Offer Letter - Please Sign Dear Candidate, Con..."
2,3,alerts@mybank.com,Unusual Login Attempt,We detected a login attempt to your account fr...,high,security,Unusual Login Attempt We detected a login atte...
5,6,spam@strange-domain.ru,"You won $1,000,000!!!",Click here to claim your lottery now. Do not s...,high,spam,"You won $1,000,000!!! Click here to claim your..."
6,7,manager@company.com,Project Update Required,Please share the status update of your project...,high,work,Project Update Required Please share the statu...

In [13]:
# security-related emails
security_emails = df[df['text'].str.contains('login|password|security', case=False, na=False)]
security_emails

,id,sender,subject,body,priority,label,text
2,3,alerts@mybank.com,Unusual Login Attempt,We detected a login attempt to your account fr...,high,security,Unusual Login Attempt We detected a login atte...
7,8,training@lms.com,Reminder: Complete Mandatory Training,Your mandatory security awareness training is ...,medium,work,Reminder: Complete Mandatory Training Your man...

In [14]:
# promotional/sale emails
promo_emails = df[df['text'].str.contains('sale|discount', case=False, na=False)]
promo_emails

,id,sender,subject,body,priority,label,text
1,2,noreply@shopping.com,Big Billion Sale is Live,Flat 70% OFF on electronics. Limited period of...,low,promotion,Big Billion Sale is Live Flat 70% OFF on elect...

In [15]:
df["priority"].value_counts()

priority
high      4
low       2
medium    2
Name: count, dtype: int64

In [16]:
df.shape

(8, 7)

In [17]:
df.isnull().sum()

id          0
sender      0
subject     0
body        0
priority    0
label       0
text        0
dtype: int64

In [18]:
df.columns

Index(['id', 'sender', 'subject', 'body', 'priority', 'label', 'text'], dtype='object')

In [19]:
df['clean_text']=df['body'].str.lower().str.replace('[^a-zA-Z]', ' ', regex=True)
df[['body', 'clean_text']].head()

,body,clean_text
0,"Dear Candidate, Congratulations! Please sign a...",dear candidate congratulations please sign a...
1,Flat 70% OFF on electronics. Limited period of...,flat off on electronics limited period of...
2,We detected a login attempt to your account fr...,we detected a login attempt to your account fr...
3,"In this week's edition, learn about AI agents,...",in this week s edition learn about ai agents ...
4,"Hey, long time no see! Are you free this weeke...",hey long time no see are you free this weeke...

In [20]:
from collections import Counter

all_words = " ".join(df['clean_text']).split()
word_freq = Counter(all_words)
word_freq.most_common(3)

[('your', 6), ('this', 4), ('please', 3)]

In [ ]:
pip install nltk

In [23]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))
filtered_words = [w for w in all_words if w not in stop_words]

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\barat\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
# Email: "Please approve the project status update urgently!"

In [ ]:
#Without NLTK
["please","approve","the","project","status","update","urgently"]

#With NLTK Stopword Removal
["please","approve","project","status","update","urgently"]