In [2]:
import pandas as pd
print("Pandas is working")

Pandas is working

In [4]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Deepalakshmi\Downloads\sample_emails.csv")
print(df.head())

   id                sender                     subject  \
0   1        hr@company.com  Offer Letter - Please Sign
1   2  noreply@shopping.com    Big Billion Sale is Live
2   3     alerts@mybank.com       Unusual Login Attempt
3   4   newsletter@blog.com      Weekly Tech Newsletter
4   5   friend123@gmail.com        Coffee this weekend?

                                                body priority       label
0  Dear Candidate, Congratulations! Please sign a...     high   important
1  Flat 70% OFF on electronics. Limited period of...      low   promotion
2  We detected a login attempt to your account fr...     high    security
3  In this week's edition, learn about AI agents,...      low  newsletter
4  Hey, long time no see! Are you free this weeke...   medium    personal

In [5]:
df.info

<bound method DataFrame.info of    id                  sender                                subject  \
0   1          hr@company.com             Offer Letter - Please Sign
1   2    noreply@shopping.com               Big Billion Sale is Live
2   3       alerts@mybank.com                  Unusual Login Attempt
3   4     newsletter@blog.com                 Weekly Tech Newsletter
4   5     friend123@gmail.com                   Coffee this weekend?
5   6  spam@strange-domain.ru                  You won $1,000,000!!!
6   7     manager@company.com                Project Update Required
7   8        training@lms.com  Reminder: Complete Mandatory Training

                                                body priority       label
0  Dear Candidate, Congratulations! Please sign a...     high   important
1  Flat 70% OFF on electronics. Limited period of...      low   promotion
2  We detected a login attempt to your account fr...     high    security
3  In this week's edition, learn about AI agents,...      low  newsletter
4  Hey, long time no see! Are you free this weeke...   medium    personal
5  Click here to claim your lottery now. Do not s...     high        spam
6  Please share the status update of your project...     high        work
7  Your mandatory security awareness training is ...   medium        work  >

In [6]:
df.describe(include="all")

,id,sender,subject,body,priority,label
count,8.00000,8,8,8,8,8
unique,NaN,8,8,8,3,7
top,NaN,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,work
freq,NaN,1,1,1,4,2
mean,4.50000,NaN,NaN,NaN,NaN,NaN
std,2.44949,NaN,NaN,NaN,NaN,NaN
min,1.00000,NaN,NaN,NaN,NaN,NaN
25%,2.75000,NaN,NaN,NaN,NaN,NaN
50%,4.50000,NaN,NaN,NaN,NaN,NaN
75%,6.25000,NaN,NaN,NaN,NaN,NaN
max,8.00000,NaN,NaN,NaN,NaN,NaN

In [7]:
df["label"].value_counts()

label
work          2
promotion     1
important     1
security      1
newsletter    1
personal      1
spam          1
Name: count, dtype: int64

In [8]:
df.fillna("")

,id,sender,subject,body,priority,label
0,1,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,important
1,2,noreply@shopping.com,Big Billion Sale is Live,Flat 70% OFF on electronics. Limited period of...,low,promotion
2,3,alerts@mybank.com,Unusual Login Attempt,We detected a login attempt to your account fr...,high,security
3,4,newsletter@blog.com,Weekly Tech Newsletter,"In this week's edition, learn about AI agents,...",low,newsletter
4,5,friend123@gmail.com,Coffee this weekend?,"Hey, long time no see! Are you free this weeke...",medium,personal
5,6,spam@strange-domain.ru,"You won $1,000,000!!!",Click here to claim your lottery now. Do not s...,high,spam
6,7,manager@company.com,Project Update Required,Please share the status update of your project...,high,work
7,8,training@lms.com,Reminder: Complete Mandatory Training,Your mandatory security awareness training is ...,medium,work

In [11]:
#Clean text + handle missing values
df = df.fillna("")
df['subject'] = df['subject'].str.lower().str.strip()
df['body'] = df['body'].str.lower().str.strip()
print(df)

   id                  sender                                subject  \
0   1          hr@company.com             offer letter - please sign
1   2    noreply@shopping.com               big billion sale is live
2   3       alerts@mybank.com                  unusual login attempt
3   4     newsletter@blog.com                 weekly tech newsletter
4   5     friend123@gmail.com                   coffee this weekend?
5   6  spam@strange-domain.ru                  you won $1,000,000!!!
6   7     manager@company.com                project update required
7   8        training@lms.com  reminder: complete mandatory training

                                                body priority       label
0  dear candidate, congratulations! please sign a...     high   important
1  flat 70% off on electronics. limited period of...      low   promotion
2  we detected a login attempt to your account fr...     high    security
3  in this week's edition, learn about ai agents,...      low  newsletter
4  hey, long time no see! are you free this weeke...   medium    personal
5  click here to claim your lottery now. do not s...     high        spam
6  please share the status update of your project...     high        work
7  your mandatory security awareness training is ...   medium        work

In [ ]:
# 2. Create combined text column
df['combined'] = df['subject'] + " " + df['body']


print(df)

   id                  sender                                subject  \
0   1          hr@company.com             offer letter - please sign
1   2    noreply@shopping.com               big billion sale is live
2   3       alerts@mybank.com                  unusual login attempt
3   4     newsletter@blog.com                 weekly tech newsletter
4   5     friend123@gmail.com                   coffee this weekend?
5   6  spam@strange-domain.ru                  you won $1,000,000!!!
6   7     manager@company.com                project update required
7   8        training@lms.com  reminder: complete mandatory training

                                                body priority       label  \
0  dear candidate, congratulations! please sign a...     high   important
1  flat 70% off on electronics. limited period of...      low   promotion
2  we detected a login attempt to your account fr...     high    security
3  in this week's edition, learn about ai agents,...      low  newsletter
4  hey, long time no see! are you free this weeke...   medium    personal
5  click here to claim your lottery now. do not s...     high        spam
6  please share the status update of your project...     high        work
7  your mandatory security awareness training is ...   medium        work

                                            combined
0  offer letter - please sign dear candidate, con...
1  big billion sale is live flat 70% off on elect...
2  unusual login attempt we detected a login atte...
3  weekly tech newsletter in this week's edition,...
4  coffee this weekend? hey, long time no see! ar...
5  you won $1,000,000!!! click here to claim your...
6  project update required please share the statu...
7  reminder: complete mandatory training your man...

In [15]:
# 3. Filter example (messages containing 'otp')
offer_only = df[df['combined'].str.contains("offer")]


print(df)
print("\nOffer Messages:")
print(offer_only)

   id                  sender                                subject  \
0   1          hr@company.com             offer letter - please sign
1   2    noreply@shopping.com               big billion sale is live
2   3       alerts@mybank.com                  unusual login attempt
3   4     newsletter@blog.com                 weekly tech newsletter
4   5     friend123@gmail.com                   coffee this weekend?
5   6  spam@strange-domain.ru                  you won $1,000,000!!!
6   7     manager@company.com                project update required
7   8        training@lms.com  reminder: complete mandatory training

                                                body priority       label  \
0  dear candidate, congratulations! please sign a...     high   important
1  flat 70% off on electronics. limited period of...      low   promotion
2  we detected a login attempt to your account fr...     high    security
3  in this week's edition, learn about ai agents,...      low  newsletter
4  hey, long time no see! are you free this weeke...   medium    personal
5  click here to claim your lottery now. do not s...     high        spam
6  please share the status update of your project...     high        work
7  your mandatory security awareness training is ...   medium        work

                                            combined
0  offer letter - please sign dear candidate, con...
1  big billion sale is live flat 70% off on elect...
2  unusual login attempt we detected a login atte...
3  weekly tech newsletter in this week's edition,...
4  coffee this weekend? hey, long time no see! ar...
5  you won $1,000,000!!! click here to claim your...
6  project update required please share the statu...
7  reminder: complete mandatory training your man...

Offer Messages:
   id                sender                     subject  \
0   1        hr@company.com  offer letter - please sign
1   2  noreply@shopping.com    big billion sale is live

                                                body priority      label  \
0  dear candidate, congratulations! please sign a...     high  important
1  flat 70% off on electronics. limited period of...      low  promotion

                                            combined
0  offer letter - please sign dear candidate, con...
1  big billion sale is live flat 70% off on elect...

In [16]:
important_only = df[df['label'].str.contains("important")]
print(important_only)

   id          sender                     subject  \
0   1  hr@company.com  offer letter - please sign

                                                body priority      label  \
0  dear candidate, congratulations! please sign a...     high  important

                                            combined
0  offer letter - please sign dear candidate, con...