In [ ]:
import pandas as pd
print("Pandas is working fine")

In [9]:
import pandas as pd
df = pd.read_csv("../data/sample_emails.csv")
df.head()

,id,sender,subject,body,priority,label
0,1,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,important
1,2,noreply@shopping.com,Big Billion Sale is Live,Flat 70% OFF on electronics. Limited period of...,low,promotion
2,3,alerts@mybank.com,Unusual Login Attempt,We detected a login attempt to your account fr...,high,security
3,4,newsletter@blog.com,Weekly Tech Newsletter,"In this week's edition, learn about AI agents,...",low,newsletter
4,5,friend123@gmail.com,Coffee this weekend?,"Hey, long time no see! Are you free this weeke...",medium,personal

In [11]:
df["label"].value_counts()

label
work          2
promotion     1
important     1
security      1
newsletter    1
personal      1
spam          1
Name: count, dtype: int64

In [3]:
import pandas as pd
import numpy as np
import re

# Load data
df = pd.read_csv("../data/sample_emails.csv")

# Quick look
print(df.shape)
print(df.columns)
df.head()

(8, 6)
Index(['id', 'sender', 'subject', 'body', 'priority', 'label'], dtype='object')

,id,sender,subject,body,priority,label
0,1,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,important
1,2,noreply@shopping.com,Big Billion Sale is Live,Flat 70% OFF on electronics. Limited period of...,low,promotion
2,3,alerts@mybank.com,Unusual Login Attempt,We detected a login attempt to your account fr...,high,security
3,4,newsletter@blog.com,Weekly Tech Newsletter,"In this week's edition, learn about AI agents,...",low,newsletter
4,5,friend123@gmail.com,Coffee this weekend?,"Hey, long time no see! Are you free this weeke...",medium,personal

In [5]:
# Standardize column names if needed
df.columns = [c.strip().lower() for c in df.columns]

# Assume columns are named 'subject' and 'body'
SUBJECT_COL = 'subject'
BODY_COL = 'body'   # change to 'message' or whatever your CSV uses if needed

# Drop rows where both subject and body are missing
df = df.dropna(subset=[SUBJECT_COL, BODY_COL], how="all")

# Fill remaining NaNs in text columns with empty string
df[SUBJECT_COL] = df[SUBJECT_COL].fillna("")
df[BODY_COL] = df[BODY_COL].fillna("")

In [6]:
def clean_text(text: str) -> str:
    if not isinstance(text, str):
        return ""
    
    # Lowercase
    text = text.lower()
    
    # Remove HTML tags
    text = re.sub(r"<.*?>", " ", text)
    
    # Remove URLs
    text = re.sub(r"http\S+|www\.\S+", " ", text)
    
    # Remove non-alphanumeric characters except basic punctuation
    text = re.sub(r"[^a-z0-9@.,!?'\s]", " ", text)
    
    # Collapse multiple spaces
    text = re.sub(r"\s+", " ", text).strip()
    
    return text

df["subject_clean"] = df[SUBJECT_COL].apply(clean_text)
df["body_clean"] = df[BODY_COL].apply(clean_text)

df[["subject", "subject_clean", "body", "body_clean"]].head()

,subject,subject_clean,body,body_clean
0,Offer Letter - Please Sign,offer letter please sign,"Dear Candidate, Congratulations! Please sign a...","dear candidate, congratulations! please sign a..."
1,Big Billion Sale is Live,big billion sale is live,Flat 70% OFF on electronics. Limited period of...,flat 70 off on electronics. limited period off...
2,Unusual Login Attempt,unusual login attempt,We detected a login attempt to your account fr...,we detected a login attempt to your account fr...
3,Weekly Tech Newsletter,weekly tech newsletter,"In this week's edition, learn about AI agents,...","in this week's edition, learn about ai agents,..."
4,Coffee this weekend?,coffee this weekend?,"Hey, long time no see! Are you free this weeke...","hey, long time no see! are you free this weeke..."

In [5]:
df["combined_text"] = (
    df["subject_clean"].fillna("") + " " + df["body_clean"].fillna("")
).str.strip()

df[["subject_clean", "body_clean", "combined_text"]].head()
print("Data loaded and initial processing done.")

NameError: name 'df' is not defined

In [6]:
import pandas as pd
df = pd.read_csv("../data/sample_emails.csv")   # or your file path

In [7]:
df['subject'] = df['subject'].fillna("")
df['body'] = df['body'].fillna("")
df['subject_clean'] = df['subject'].apply(clean_text)
df['body_clean'] = df['body'].apply(clean_text)

NameError: name 'clean_text' is not defined

In [8]:
import pandas as pd
import re

# 1) Load the CSV and create df
df = pd.read_csv("../data/sample_emails.csv")

# 2) Handle missing values
df = df.dropna(subset=["subject", "body"], how="all")
df["subject"] = df["subject"].fillna("")
df["body"] = df["body"].fillna("")

# 3) DEFINE clean_text BEFORE using it
def clean_text(text):
    text = text.lower()                              # make lowercase
    text = re.sub(r"<.*?>", " ", text)               # remove HTML tags
    text = re.sub(r"http\S+|www\.\S+", " ", text)    # remove URLs
    text = re.sub(r"[^a-z0-9@.,!?'\s]", " ", text)   # remove weird symbols
    text = re.sub(r"\s+", " ", text).strip()         # fix extra spaces
    return text

# 4) Use clean_text to create cleaned columns
df["subject_clean"] = df["subject"].apply(clean_text)
df["body_clean"]   = df["body"].apply(clean_text)

# 5) Create combined text column (subject + body)
df["combined_text"] = df["subject_clean"] + " " + df["body_clean"]

df.head()

,id,sender,subject,body,priority,label,subject_clean,body_clean,combined_text
0,1,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,important,offer letter please sign,"dear candidate, congratulations! please sign a...","offer letter please sign dear candidate, congr..."
1,2,noreply@shopping.com,Big Billion Sale is Live,Flat 70% OFF on electronics. Limited period of...,low,promotion,big billion sale is live,flat 70 off on electronics. limited period off...,big billion sale is live flat 70 off on electr...
2,3,alerts@mybank.com,Unusual Login Attempt,We detected a login attempt to your account fr...,high,security,unusual login attempt,we detected a login attempt to your account fr...,unusual login attempt we detected a login atte...
3,4,newsletter@blog.com,Weekly Tech Newsletter,"In this week's edition, learn about AI agents,...",low,newsletter,weekly tech newsletter,"in this week's edition, learn about ai agents,...","weekly tech newsletter in this week's edition,..."
4,5,friend123@gmail.com,Coffee this weekend?,"Hey, long time no see! Are you free this weeke...",medium,personal,coffee this weekend?,"hey, long time no see! are you free this weeke...","coffee this weekend? hey, long time no see! ar..."