In [1]:
import pandas as pd
print("pandas is working")

pandas is working

In [2]:
import pandas as pd
df =pd.read_csv("../data/sample_emails.csv")
df.head()
# df.tail()

,id,sender,subject,body,priority,label
0,1,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,important
1,2,noreply@shopping.com,Big Billion Sale is Live,Flat 70% OFF on electronics. Limited period of...,low,promotion
2,3,alerts@mybank.com,Unusual Login Attempt,We detected a login attempt to your account fr...,high,security
3,4,newsletter@blog.com,Weekly Tech Newsletter,"In this week's edition, learn about AI agents,...",low,newsletter
4,5,friend123@gmail.com,Coffee this weekend?,"Hey, long time no see! Are you free this weeke...",medium,personal

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        8 non-null      int64
 1   sender    8 non-null      object
 2   subject   8 non-null      object
 3   body      8 non-null      object
 4   priority  8 non-null      object
 5   label     8 non-null      object
dtypes: int64(1), object(5)
memory usage: 516.0+ bytes

In [4]:
# df["important"].value_counts()
(df["label"] == "important").sum()

1

In [5]:
high_priority = df[df["priority"]=="high"]
print(high_priority)

   id                  sender                     subject  \
0   1          hr@company.com  Offer Letter - Please Sign
2   3       alerts@mybank.com       Unusual Login Attempt
5   6  spam@strange-domain.ru       You won $1,000,000!!!
6   7     manager@company.com     Project Update Required

                                                body priority      label
0  Dear Candidate, Congratulations! Please sign a...     high  important
2  We detected a login attempt to your account fr...     high   security
5  Click here to claim your lottery now. Do not s...     high       spam
6  Please share the status update of your project...     high       work

In [6]:
important_cols = df[["subject","sender"]]
important_cols.head()

                      subject                sender
0  Offer Letter - Please Sign        hr@company.com
1    Big Billion Sale is Live  noreply@shopping.com
2       Unusual Login Attempt     alerts@mybank.com
3      Weekly Tech Newsletter   newsletter@blog.com
4        Coffee this weekend?   friend123@gmail.com

In [7]:
import pandas as pd
df =pd.read_csv("../data/sample_emails.csv")
df.head()
# df.tail()

,id,sender,subject,body,priority,label
0,1,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,important
1,2,noreply@shopping.com,Big Billion Sale is Live,Flat 70% OFF on electronics. Limited period of...,low,promotion
2,3,alerts@mybank.com,Unusual Login Attempt,We detected a login attempt to your account fr...,high,security
3,4,newsletter@blog.com,Weekly Tech Newsletter,"In this week's edition, learn about AI agents,...",low,newsletter
4,5,friend123@gmail.com,Coffee this weekend?,"Hey, long time no see! Are you free this weeke...",medium,personal

In [8]:
df.describe(include="all")

,id,sender,subject,body,priority,label
count,8.00000,8,8,8,8,8
unique,NaN,8,8,8,3,7
top,NaN,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,work
freq,NaN,1,1,1,4,2
mean,4.50000,NaN,NaN,NaN,NaN,NaN
std,2.44949,NaN,NaN,NaN,NaN,NaN
min,1.00000,NaN,NaN,NaN,NaN,NaN
25%,2.75000,NaN,NaN,NaN,NaN,NaN
50%,4.50000,NaN,NaN,NaN,NaN,NaN
75%,6.25000,NaN,NaN,NaN,NaN,NaN
max,8.00000,NaN,NaN,NaN,NaN,NaN

In [9]:
df["label"].value_counts()

label
work          2
important     1
promotion     1
security      1
newsletter    1
personal      1
spam          1
Name: count, dtype: int64

In [10]:
df = df.fillna("")

df["subject"] = df["subject"].str.lower().str.strip()
df["body"] = df["body"].str.lower().str.strip()

In [11]:
df["combined_text"] = df["subject"] + " " + df["body"]
df[["subject", "body", "combined_text"]].head()

,subject,body,combined_text
0,offer letter - please sign,"dear candidate, congratulations! please sign a...","offer letter - please sign dear candidate, con..."
1,big billion sale is live,flat 70% off on electronics. limited period of...,big billion sale is live flat 70% off on elect...
2,unusual login attempt,we detected a login attempt to your account fr...,unusual login attempt we detected a login atte...
3,weekly tech newsletter,"in this week's edition, learn about ai agents,...","weekly tech newsletter in this week's edition,..."
4,coffee this weekend?,"hey, long time no see! are you free this weeke...","coffee this weekend? hey, long time no see! ar..."

In [21]:
spam_keywords = [ "sale", "free", "win", "won", "lottery", "discount", "click"]

df["is_spam"] = df["combined_text"].apply(
    lambda text: any(word in text for word in spam_keywords)
)
df["spam_label"] = df["is_spam"].apply(lambda x: "spam" if x else "not spam")

In [22]:
print("SPAM EMAILS:")
print(df[df["spam_label"] == "spam"])

print("\nNOT SPAM EMAILS:")
print(df[df["spam_label"] == "not spam"])

SPAM EMAILS:
   id                  sender                   subject  \
1   2    noreply@shopping.com  big billion sale is live
4   5     friend123@gmail.com      coffee this weekend?
5   6  spam@strange-domain.ru     you won $1,000,000!!!

                                                body priority      label  \
1  flat 70% off on electronics. limited period of...      low  promotion
4  hey, long time no see! are you free this weeke...   medium   personal
5  click here to claim your lottery now. do not s...     high       spam

                                       combined_text  is_spam spam_label
1  big billion sale is live flat 70% off on elect...     True       spam
4  coffee this weekend? hey, long time no see! ar...     True       spam
5  you won $1,000,000!!! click here to claim your...     True       spam

NOT SPAM EMAILS:
   id               sender                                subject  \
0   1       hr@company.com             offer letter - please sign
2   3    alerts@mybank.com                  unusual login attempt
3   4  newsletter@blog.com                 weekly tech newsletter
6   7  manager@company.com                project update required
7   8     training@lms.com  reminder: complete mandatory training

                                                body priority       label  \
0  dear candidate, congratulations! please sign a...     high   important
2  we detected a login attempt to your account fr...     high    security
3  in this week's edition, learn about ai agents,...      low  newsletter
6  please share the status update of your project...     high        work
7  your mandatory security awareness training is ...   medium        work

                                       combined_text  is_spam spam_label
0  offer letter - please sign dear candidate, con...    False   not spam
2  unusual login attempt we detected a login atte...    False   not spam
3  weekly tech newsletter in this week's edition,...    False   not spam
6  project update required please share the statu...    False   not spam
7  reminder: complete mandatory training your man...    False   not spam

In [ ]:
import pandas as pd
df =pd.read_csv("../data/sample_emails.csv")
# df.head()
df.info()

,id,sender,subject,body,priority,label
0,1,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,important
1,2,noreply@shopping.com,Big Billion Sale is Live,Flat 70% OFF on electronics. Limited period of...,low,promotion
2,3,alerts@mybank.com,Unusual Login Attempt,We detected a login attempt to your account fr...,high,security
3,4,newsletter@blog.com,Weekly Tech Newsletter,"In this week's edition, learn about AI agents,...",low,newsletter
4,5,friend123@gmail.com,Coffee this weekend?,"Hey, long time no see! Are you free this weeke...",medium,personal

In [4]:
df.shape

(8, 6)

In [5]:
df.isnull().sum()

id          0
sender      0
subject     0
body        0
priority    0
label       0
dtype: int64

In [7]:
df['label'].value_counts()

label
work          2
important     1
promotion     1
security      1
newsletter    1
personal      1
spam          1
Name: count, dtype: int64

In [8]:
df['priority'].value_counts()

priority
high      4
low       2
medium    2
Name: count, dtype: int64

In [9]:
df['clean_text']=df['body'].str.lower().str.replace('[^a-zA-Z]','',regex=True)

In [11]:
df.columns

Index(['id', 'sender', 'subject', 'body', 'priority', 'label', 'clean_text'], dtype='object')

In [13]:
df['clean_text'] = df['body'].str.lower().str.replace('[^a-zA-Z]','',regex=True)
df[['body','clean_text']].head()

,body,clean_text
0,"Dear Candidate, Congratulations! Please sign a...",dearcandidatecongratulationspleasesignanduploa...
1,Flat 70% OFF on electronics. Limited period of...,flatoffonelectronicslimitedperiodoffervisitour...
2,We detected a login attempt to your account fr...,wedetectedaloginattempttoyouraccountfromanewde...
3,"In this week's edition, learn about AI agents,...",inthisweekseditionlearnaboutaiagentslanggrapha...
4,"Hey, long time no see! Are you free this weeke...",heylongtimenoseeareyoufreethisweekendforcoffee