In [1]:
import pandas as pd
print("Pandas is Working")

Pandas is Working

In [2]:
import pandas as pd
df = pd.read_csv("../data/sample_emails.csv")
df.head()

,id,sender,subject,body,priority,label
0,1,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,important
1,2,noreply@shopping.com,Big Billion Sale is Live,Flat 70% OFF on electronics. Limited period of...,low,promotion
2,3,alerts@mybank.com,Unusual Login Attempt,We detected a login attempt to your account fr...,high,security
3,4,newsletter@blog.com,Weekly Tech Newsletter,"In this week's edition, learn about AI agents,...",low,newsletter
4,5,friend123@gmail.com,Coffee this weekend?,"Hey, long time no see! Are you free this weeke...",medium,personal

In [1]:
df.info()

NameError: name 'df' is not defined

In [2]:
df[important].value_counts()

NameError: name 'df' is not defined

In [3]:
high_priority = df[df["Priority"] == "High]"
"high_priority"

_IncompleteInputError: incomplete input (1789106206.py, line 2)

In [4]:
important_cols = df[["Subject", "Sender"]]
important_cols.head()

NameError: name 'df' is not defined

In [5]:
important_cols = df[["subject", "sender"]]
important_cols.head()

NameError: name 'df' is not defined

In [7]:

import pandas as pd
df = pd.read_csv("../data/sample_emails.csv")
df.head()

,id,sender,subject,body,priority,label
0,1,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,important
1,2,noreply@shopping.com,Big Billion Sale is Live,Flat 70% OFF on electronics. Limited period of...,low,promotion
2,3,alerts@mybank.com,Unusual Login Attempt,We detected a login attempt to your account fr...,high,security
3,4,newsletter@blog.com,Weekly Tech Newsletter,"In this week's edition, learn about AI agents,...",low,newsletter
4,5,friend123@gmail.com,Coffee this weekend?,"Hey, long time no see! Are you free this weeke...",medium,personal

In [8]:
df.columns

Index(['id', 'sender', 'subject', 'body', 'priority', 'label'], dtype='object')

In [9]:
df.info

<bound method DataFrame.info of    id                  sender                                subject  \
0   1          hr@company.com             Offer Letter - Please Sign
1   2    noreply@shopping.com               Big Billion Sale is Live
2   3       alerts@mybank.com                  Unusual Login Attempt
3   4     newsletter@blog.com                 Weekly Tech Newsletter
4   5     friend123@gmail.com                   Coffee this weekend?
5   6  spam@strange-domain.ru                  You won $1,000,000!!!
6   7     manager@company.com                Project Update Required
7   8        training@lms.com  Reminder: Complete Mandatory Training

                                                body priority       label
0  Dear Candidate, Congratulations! Please sign a...     high   important
1  Flat 70% OFF on electronics. Limited period of...      low   promotion
2  We detected a login attempt to your account fr...     high    security
3  In this week's edition, learn about AI agents,...      low  newsletter
4  Hey, long time no see! Are you free this weeke...   medium    personal
5  Click here to claim your lottery now. Do not s...     high        spam
6  Please share the status update of your project...     high        work
7  Your mandatory security awareness training is ...   medium        work  >

In [10]:
df.describe(include="all")

,id,sender,subject,body,priority,label
count,8.00000,8,8,8,8,8
unique,NaN,8,8,8,3,7
top,NaN,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,work
freq,NaN,1,1,1,4,2
mean,4.50000,NaN,NaN,NaN,NaN,NaN
std,2.44949,NaN,NaN,NaN,NaN,NaN
min,1.00000,NaN,NaN,NaN,NaN,NaN
25%,2.75000,NaN,NaN,NaN,NaN,NaN
50%,4.50000,NaN,NaN,NaN,NaN,NaN
75%,6.25000,NaN,NaN,NaN,NaN,NaN
max,8.00000,NaN,NaN,NaN,NaN,NaN

In [11]:
df["label"].value_counts()

label
work          2
promotion     1
important     1
security      1
newsletter    1
personal      1
spam          1
Name: count, dtype: int64

In [4]:
import pandas as pd
df = pd.read_csv("../data/sample_emails.csv")
df.head()

,id,sender,subject,body,priority,label
0,1,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,important
1,2,noreply@shopping.com,Big Billion Sale is Live,Flat 70% OFF on electronics. Limited period of...,low,promotion
2,3,alerts@mybank.com,Unusual Login Attempt,We detected a login attempt to your account fr...,high,security
3,4,newsletter@blog.com,Weekly Tech Newsletter,"In this week's edition, learn about AI agents,...",low,newsletter
4,5,friend123@gmail.com,Coffee this weekend?,"Hey, long time no see! Are you free this weeke...",medium,personal

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        8 non-null      int64
 1   sender    8 non-null      object
 2   subject   8 non-null      object
 3   body      8 non-null      object
 4   priority  8 non-null      object
 5   label     8 non-null      object
dtypes: int64(1), object(5)
memory usage: 516.0+ bytes

In [6]:
df.shape

(8, 6)

In [7]:
df.isnull().sum()

id          0
sender      0
subject     0
body        0
priority    0
label       0
dtype: int64

In [8]:
df['email_body'][0]

KeyError: 'email_body'

In [10]:
df['label'].value_counts()

label
work          2
promotion     1
important     1
security      1
newsletter    1
personal      1
spam          1
Name: count, dtype: int64

In [11]:
df['priority'].value_counts()

priority
high      4
low       2
medium    2
Name: count, dtype: int64

In [14]:
df['clean_text'] = 
df['body'].str.lower().str.replace('[^a-zA-Z]',",regex=True)

SyntaxError: unterminated string literal (detected at line 2) (580886863.py, line 2)

In [15]:
df.columns

Index(['id', 'sender', 'subject', 'body', 'priority', 'label'], dtype='object')

In [19]:
df['clean_text'] = df['body'].str.lower().str.replace('[^a-zA-Z]','',regex=True)
df[['body','clean_text']].head()

,body,clean_text
0,"Dear Candidate, Congratulations! Please sign a...",dearcandidatecongratulationspleasesignanduploa...
1,Flat 70% OFF on electronics. Limited period of...,flatoffonelectronicslimitedperiodoffervisitour...
2,We detected a login attempt to your account fr...,wedetectedaloginattempttoyouraccountfromanewde...
3,"In this week's edition, learn about AI agents,...",inthisweekseditionlearnaboutaiagentslanggrapha...
4,"Hey, long time no see! Are you free this weeke...",heylongtimenoseeareyoufreethisweekendforcoffee

In [1]:
import pandas as pd
df = pd.read_csv("../data/sample_emails.csv")
df.head()

,id,sender,subject,body,priority,label
0,1,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,important
1,2,noreply@shopping.com,Big Billion Sale is Live,Flat 70% OFF on electronics. Limited period of...,low,promotion
2,3,alerts@mybank.com,Unusual Login Attempt,We detected a login attempt to your account fr...,high,security
3,4,newsletter@blog.com,Weekly Tech Newsletter,"In this week's edition, learn about AI agents,...",low,newsletter
4,5,friend123@gmail.com,Coffee this weekend?,"Hey, long time no see! Are you free this weeke...",medium,personal

In [3]:
from collections import Counter

all_words = " ".join(df['clean_text']).split()
word_freq = Counter(all_words)
word_freq.most_common(15)

KeyError: 'clean_text'

In [4]:
all_words_text = "".join(df['clean_text'])

KeyError: 'clean_text'

In [5]:
df.colums

AttributeError: 'DataFrame' object has no attribute 'colums'

In [6]:
import pandas as pd
df = pd.read_csv("../data/sample_emails.csv")
df.head()

,id,sender,subject,body,priority,label
0,1,hr@company.com,Offer Letter - Please Sign,"Dear Candidate, Congratulations! Please sign a...",high,important
1,2,noreply@shopping.com,Big Billion Sale is Live,Flat 70% OFF on electronics. Limited period of...,low,promotion
2,3,alerts@mybank.com,Unusual Login Attempt,We detected a login attempt to your account fr...,high,security
3,4,newsletter@blog.com,Weekly Tech Newsletter,"In this week's edition, learn about AI agents,...",low,newsletter
4,5,friend123@gmail.com,Coffee this weekend?,"Hey, long time no see! Are you free this weeke...",medium,personal

In [7]:
df.columns

Index(['id', 'sender', 'subject', 'body', 'priority', 'label'], dtype='object')

In [8]:
df['clean_text'] =

SyntaxError: invalid syntax (3040335918.py, line 1)

In [9]:
df['clean_text'] = df['body'].str.lower().str.replace('[^a-zA-Z]','',regex=True)
df[['body','clean_text']].head()

,body,clean_text
0,"Dear Candidate, Congratulations! Please sign a...",dearcandidatecongratulationspleasesignanduploa...
1,Flat 70% OFF on electronics. Limited period of...,flatoffonelectronicslimitedperiodoffervisitour...
2,We detected a login attempt to your account fr...,wedetectedaloginattempttoyouraccountfromanewde...
3,"In this week's edition, learn about AI agents,...",inthisweekseditionlearnaboutaiagentslanggrapha...
4,"Hey, long time no see! Are you free this weeke...",heylongtimenoseeareyoufreethisweekendforcoffee

In [10]:
all_words_text = " ".join(df['clean_text'])

In [11]:
words = all_words_text.split()

In [12]:
len(words)

8

In [13]:
import nltk

ModuleNotFoundError: No module named 'nltk'

In [14]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))
filtered_words = [w for w in words if w not in stop_words]

ModuleNotFoundError: No module named 'nltk'

In [15]:
pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Collecting nltk
  Downloading nltk-3.9.2-py3-none-any.whl.metadata (3.2 kB)
Collecting click (from nltk)
  Using cached click-8.3.1-py3-none-any.whl.metadata (2.6 kB)
Collecting joblib (from nltk)
  Using cached joblib-1.5.2-py3-none-any.whl.metadata (5.6 kB)
Collecting regex>=2021.8.3 (from nltk)
  Using cached regex-2025.11.3-cp313-cp313-win_amd64.whl.metadata (41 kB)
Collecting tqdm (from nltk)
  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: colorama in c:\users\pantla\appdata\roaming\python\python313\site-packages (from click->nltk) (0.4.6)
Using cached nltk-3.9.2-py3-none-any.whl (1.5 MB)
Using cached regex-2025.11.3-cp313-cp313-win_amd64.whl (277 kB)
Downloading click-8.3.1-py3-none-any.whl (108 kB)
Downloading joblib-1.5.2-py3-none-any.whl (308 kB)
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
Installing collected packages: tqdm, regex, joblib, click, nltk
Successfully installed click-8.3.1 joblib-1.5.2 nltk-3.9.2 regex-2025.11.3 tqdm-4.67.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [16]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))
filtered_words = [w for w in words if w not in stop_words]

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Pantla\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

In [17]:
# Email: "Please approve the project status update urgently!"

In [ ]:
# Without NLTK 
["please", "approve","the","project","status","update","urgently"]

#With NLTK
["approv","project","status","updat","urgent"]