In [ ]:
!pip install pandas nltk
import pandas as pd
import nltk
nltk.download('punkt')
nltk.download('stopwords')

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\pantla\appdata\roaming\python\python313\site-packages (2.3.3)
Requirement already satisfied: nltk in c:\users\pantla\appdata\roaming\python\python313\site-packages (3.9.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\pantla\appdata\roaming\python\python313\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pantla\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\pantla\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\pantla\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: click in c:\users\pantla\appdata\roaming\python\python313\site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in c:\users\pantla\appdata\roaming\python\python313\site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\pantla\appdata\roaming\python\python313\site-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in c:\users\pantla\appdata\roaming\python\python313\site-packages (from nltk) (4.67.1)
Requirement already satisfied: six>=1.5 in c:\users\pantla\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: colorama in c:\users\pantla\appdata\roaming\python\python313\site-packages (from click->nltk) (0.4.6)

[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Pantla\AppData\Roaming\nltk_data...

In [1]:
df = pd.read_csv("../data/sample_emails_with_triage_200.csv")
df.head()

NameError: name 'pd' is not defined

In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
import re

In [5]:
df = pd.read_csv("../data/sample_emails_with_triage_200.csv")
df.head()

,id,sender,subject,body,priority,triage_label
0,1,alerts@bank.com,Password Reset Request,Reminder: The client meeting is scheduled at 1...,low,notify_human
1,2,alerts@bank.com,Congratulations! You've Won,Your invoice of INR 25515.09 is due on 2025-12...,low,respond
2,3,no-reply@service.com,Promotion: Big Sale,Reminder: The client meeting is scheduled at 1...,low,ignore
3,4,sales@shop.com,Monthly Report,"Hello team, please find the attached weekly re...",medium,respond
4,5,no-reply@service.com,Survey,"Hello team, please find the attached weekly re...",low,respond

In [10]:
import pandas as pd
df = pd.read_csv("../data/sample_emails_with_triage_200.csv")
df.head()

,id,sender,subject,body,priority,triage_label
0,1,alerts@bank.com,Password Reset Request,Reminder: The client meeting is scheduled at 1...,low,notify_human
1,2,alerts@bank.com,Congratulations! You've Won,Your invoice of INR 25515.09 is due on 2025-12...,low,respond
2,3,no-reply@service.com,Promotion: Big Sale,Reminder: The client meeting is scheduled at 1...,low,ignore
3,4,sales@shop.com,Monthly Report,"Hello team, please find the attached weekly re...",medium,respond
4,5,no-reply@service.com,Survey,"Hello team, please find the attached weekly re...",low,respond

In [12]:
df['clean_text'] = (
    df['body']
    .str.lower()
    .str.replace('[^a-zA-Z ]', '', regex=True)
)

df[['body', 'clean_text']].head()

,body,clean_text
0,Reminder: The client meeting is scheduled at 1...,reminder the client meeting is scheduled at t...
1,Your invoice of INR 25515.09 is due on 2025-12...,your invoice of inr is due on please pay to ...
2,Reminder: The client meeting is scheduled at 1...,reminder the client meeting is scheduled at t...
3,"Hello team, please find the attached weekly re...",hello team please find the attached weekly rep...
4,"Hello team, please find the attached weekly re...",hello team please find the attached weekly rep...

In [13]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

stop_words = set(stopwords.words("english"))

df['keywords'] = df['clean_text'].apply(
    lambda x: [w for w in x.split() if w not in stop_words]
)

df[['clean_text', 'keywords']].head()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Pantla\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,clean_text,keywords
0,reminder the client meeting is scheduled at t...,"[reminder, client, meeting, scheduled, tomorro..."
1,your invoice of inr is due on please pay to ...,"[invoice, inr, due, please, pay, avoid, late, ..."
2,reminder the client meeting is scheduled at t...,"[reminder, client, meeting, scheduled, tomorro..."
3,hello team please find the attached weekly rep...,"[hello, team, please, find, attached, weekly, ..."
4,hello team please find the attached weekly rep...,"[hello, team, please, find, attached, weekly, ..."

In [14]:
def triage_rule(text):
    text = text.lower()

    if "refund" in text or "urgent" in text or "password" in text:
        return "notify_human"

    if "newsletter" in text or "promotion" in text:
        return "ignore"

    return "respond_or_act"

df['triage'] = df['clean_text'].apply(triage_rule)
df[['body', 'triage']].head()

                                                body          triage
0  Reminder: The client meeting is scheduled at 1...  respond_or_act
1  Your invoice of INR 25515.09 is due on 2025-12...  respond_or_act
2  Reminder: The client meeting is scheduled at 1...  respond_or_act
3  Hello team, please find the attached weekly re...  respond_or_act
4  Hello team, please find the attached weekly re...  respond_or_act

In [15]:
df.to_csv("../data/milestone1_output.csv", index=False)