In [1]:
import pandas as pd

In [2]:
import pandas as pd
import re

In [3]:
df=pd.read_csv("../data/sample_emails_with_triage_200.csv")
df.head()

,id,sender,subject,body,priority,triage_label,ideal_intent,ideal_tone
0,1,alerts@bank.com,Password Reset Request,Reminder: The client meeting is scheduled at 1...,low,notify_human,respond,neutral
1,2,alerts@bank.com,Congratulations! You've Won,Your invoice of INR 25515.09 is due on 2025-12...,low,respond,notify,neutral
2,3,no-reply@service.com,Promotion: Big Sale,Reminder: The client meeting is scheduled at 1...,low,ignore,respond,neutral
3,4,sales@shop.com,Monthly Report,"Hello team, please find the attached weekly re...",medium,respond,respond,neutral
4,5,no-reply@service.com,Survey,"Hello team, please find the attached weekly re...",low,respond,respond,neutral

In [4]:
def clean_email(text):
    if isinstance(text, str):
        text = text.lower()
        text = re.sub(r"http\S+", "", text)
        text = re.sub(r"<.*?>", "", text)
        text = re.sub(r"[^a-zA-Z0-9 ]", " ", text)
        text = re.sub(r"\s+", " ", text).strip()
        return text
    else:
        return ""
    
src_col = "email_text" if "email_text" in df.columns else "body"
df["clean_text"] = df[src_col].apply(clean_email)
df.head()
df.head()

,id,sender,subject,body,priority,triage_label,ideal_intent,ideal_tone,clean_text
0,1,alerts@bank.com,Password Reset Request,Reminder: The client meeting is scheduled at 1...,low,notify_human,respond,neutral,reminder the client meeting is scheduled at 10...
1,2,alerts@bank.com,Congratulations! You've Won,Your invoice of INR 25515.09 is due on 2025-12...,low,respond,notify,neutral,your invoice of inr 25515 09 is due on 2025 12...
2,3,no-reply@service.com,Promotion: Big Sale,Reminder: The client meeting is scheduled at 1...,low,ignore,respond,neutral,reminder the client meeting is scheduled at 11...
3,4,sales@shop.com,Monthly Report,"Hello team, please find the attached weekly re...",medium,respond,respond,neutral,hello team please find the attached weekly rep...
4,5,no-reply@service.com,Survey,"Hello team, please find the attached weekly re...",low,respond,respond,neutral,hello team please find the attached weekly rep...

In [5]:
def triage(text):
    if any(keyword in text for keyword in ["urgent", "immediately", "asap", "action required"]):
        return "respond_or_act"
    elif any(keyword in text for keyword in ["please check", "review", "verify"]):
        return "notify_human"
    else:
        return "ignore"

if "clean_text" not in df.columns:
    src_col = "email_text" if "email_text" in df.columns else "body"
    df["clean_text"] = df[src_col].apply(clean_email)

df["triage"] = df["clean_text"].apply(triage)
df.head()

,id,sender,subject,body,priority,triage_label,ideal_intent,ideal_tone,clean_text,triage
0,1,alerts@bank.com,Password Reset Request,Reminder: The client meeting is scheduled at 1...,low,notify_human,respond,neutral,reminder the client meeting is scheduled at 10...,ignore
1,2,alerts@bank.com,Congratulations! You've Won,Your invoice of INR 25515.09 is due on 2025-12...,low,respond,notify,neutral,your invoice of inr 25515 09 is due on 2025 12...,ignore
2,3,no-reply@service.com,Promotion: Big Sale,Reminder: The client meeting is scheduled at 1...,low,ignore,respond,neutral,reminder the client meeting is scheduled at 11...,ignore
3,4,sales@shop.com,Monthly Report,"Hello team, please find the attached weekly re...",medium,respond,respond,neutral,hello team please find the attached weekly rep...,ignore
4,5,no-reply@service.com,Survey,"Hello team, please find the attached weekly re...",low,respond,respond,neutral,hello team please find the attached weekly rep...,ignore

In [6]:
df.to_csv("../data/milestone1_output_swethanand-sangamreddi.csv", index=False)