In [5]:
import pandas as pd

df = pd.read_csv("../data/milestone1_arbind.csv")
df.head()

,id,sender,subject,body,priority,triage_label,clean_text,triage,triage_match,predicted_triage
0,1,alerts@bank.com,Password Reset Request,Reminder: The client meeting is scheduled at 1...,low,notify_human,reminder: the client meeting is scheduled at 1...,respond_or_act,\bmeeting\b,respond_or_act
1,2,alerts@bank.com,Congratulations! You've Won,Your invoice of INR 25515.09 is due on 2025-12...,low,respond,your invoice of inr 25515.09 is due on 2025-12...,notify_human,\binvoice\b,respond_or_act
2,3,no-reply@service.com,Promotion: Big Sale,Reminder: The client meeting is scheduled at 1...,low,ignore,reminder: the client meeting is scheduled at 1...,respond_or_act,\bmeeting\b,respond_or_act
3,4,sales@shop.com,Monthly Report,"Hello team, please find the attached weekly re...",medium,respond,"hello team, please find the attached weekly re...",respond_or_act,\battached\b,respond_or_act
4,5,no-reply@service.com,Survey,"Hello team, please find the attached weekly re...",low,respond,"hello team, please find the attached weekly re...",respond_or_act,\battached\b,respond_or_act

In [9]:
df.rpow

<bound method DataFrame.rpow of       id                sender                      subject  \
0      1       alerts@bank.com       Password Reset Request
1      2       alerts@bank.com  Congratulations! You've Won
2      3  no-reply@service.com          Promotion: Big Sale
3      4        sales@shop.com               Monthly Report
4      5  no-reply@service.com                       Survey
..   ...                   ...                          ...
195  196  no-reply@service.com                Policy Update
196  197      boss@company.com                Order Shipped
197  198  no-reply@service.com            Weekly Newsletter
198  199     news@techblog.com              Payment Overdue
199  200     support@cloud.com          Promotion: Big Sale

                                                  body priority  triage_label  \
0    Reminder: The client meeting is scheduled at 1...      low  notify_human
1    Your invoice of INR 25515.09 is due on 2025-12...      low       respond
2    Reminder: The client meeting is scheduled at 1...      low        ignore
3    Hello team, please find the attached weekly re...   medium       respond
4    Hello team, please find the attached weekly re...      low       respond
..                                                 ...      ...           ...
195  Security alert: multiple failed login attempts...      low  notify_human
196  Your order #3828 has been shipped and is expec...   medium       respond
197  Congratulations! You have been selected as a l...   medium        ignore
198  Please complete the mandatory training module ...      low  notify_human
199  Congratulations! You have been selected as a l...      low        ignore

                                            clean_text          triage  \
0    reminder: the client meeting is scheduled at 1...  respond_or_act
1    your invoice of inr 25515.09 is due on 2025-12...    notify_human
2    reminder: the client meeting is scheduled at 1...  respond_or_act
3    hello team, please find the attached weekly re...  respond_or_act
4    hello team, please find the attached weekly re...  respond_or_act
..                                                 ...             ...
195  security alert: multiple failed login attempts...  respond_or_act
196  your order #3828 has been shipped and is expec...  respond_or_act
197  congratulations! you have been selected as a l...          ignore
198  please complete the mandatory training module ...  respond_or_act
199  congratulations! you have been selected as a l...          ignore

            triage_match
0            \bmeeting\b
1            \binvoice\b
2            \bmeeting\b
3           \battached\b
4           \battached\b
..                   ...
195     default_fallback
196     default_fallback
197  \bcongratulations\b
198     default_fallback
199  \bcongratulations\b

[200 rows x 9 columns]>

In [4]:
import pandas as pd

df = pd.read_csv("../data/sample_emails_with_triage_200.csv")
df.head()

,id,sender,subject,body,priority,triage_label
0,1,alerts@bank.com,Password Reset Request,Reminder: The client meeting is scheduled at 1...,low,notify_human
1,2,alerts@bank.com,Congratulations! You've Won,Your invoice of INR 25515.09 is due on 2025-12...,low,respond
2,3,no-reply@service.com,Promotion: Big Sale,Reminder: The client meeting is scheduled at 1...,low,ignore
3,4,sales@shop.com,Monthly Report,"Hello team, please find the attached weekly re...",medium,respond
4,5,no-reply@service.com,Survey,"Hello team, please find the attached weekly re...",low,respond

In [3]:
#select 100 test emails
eval_df = df.sample(100, random_state=42)
eval_df = eval_df.reset_index(drop=True)

eval_df.head()

,id,sender,subject,body,priority,triage_label
0,96,no-reply@service.com,Weekly Newsletter,Your order #3634 has been shipped and is expec...,low,ignore
1,16,news@techblog.com,Payment Overdue,"Hi, don't miss our sale with discounts up to 7...",low,notify_human
2,31,news@techblog.com,Weekly Newsletter,Notice: Your account will be locked unless ver...,high,notify_human
3,159,no-reply@service.com,Welcome to Service,Reminder: The client meeting is scheduled at 9...,low,respond
4,129,sales@shop.com,Invoice Due,Your order #6464 has been shipped and is expec...,low,respond