In [14]:
import pandas as pd

df = pd.read_csv("../data/milestone1_arbind.csv")
df.head()

,id,sender,subject,body,priority,triage_label,ideal_intent,ideal_tone,clean_text,triage,triage_match,predicted_triage
0,1,[alerts@bank.com](mailto:alerts@bank.com),Password Reset Request,Reminder: The client meeting is scheduled at 1...,low,notify_human,respond,neutral,reminder: the client meeting is scheduled at 1...,respond_or_act,\bmeeting\b,respond_or_act
1,2,[alerts@bank.com](mailto:alerts@bank.com),Congratulations! You've Won,Your invoice of INR 25515.09 is due on 2025-12...,low,respond,respond,neutral,your invoice of inr 25515.09 is due on 2025-12...,notify_human,\binvoice\b,respond_or_act
2,3,[no-reply@service.com](mailto:no-reply@service...,Promotion: Big Sale,Reminder: The client meeting is scheduled at 1...,low,ignore,respond,neutral,reminder: the client meeting is scheduled at 1...,respond_or_act,\bmeeting\b,respond_or_act
3,4,[sales@shop.com](mailto:sales@shop.com),Monthly Report,"Hello team, please find the attached weekly re...",medium,respond,respond,polite,"hello team, please find the attached weekly re...",respond_or_act,\battached\b,respond_or_act
4,5,[no-reply@service.com](mailto:no-reply@service...,Survey,"Hello team, please find the attached weekly re...",low,respond,respond,polite,"hello team, please find the attached weekly re...",respond_or_act,\battached\b,respond_or_act

In [15]:
df.rpow

<bound method DataFrame.rpow of       id                                             sender  \
0      1          [alerts@bank.com](mailto:alerts@bank.com)
1      2          [alerts@bank.com](mailto:alerts@bank.com)
2      3  [no-reply@service.com](mailto:no-reply@service...
3      4            [sales@shop.com](mailto:sales@shop.com)
4      5  [no-reply@service.com](mailto:no-reply@service...
..   ...                                                ...
195  196  [no-reply@service.com](mailto:no-reply@service...
196  197        [boss@company.com](mailto:boss@company.com)
197  198  [no-reply@service.com](mailto:no-reply@service...
198  199      [news@techblog.com](mailto:news@techblog.com)
199  200      [support@cloud.com](mailto:support@cloud.com)

                         subject  \
0         Password Reset Request
1    Congratulations! You've Won
2            Promotion: Big Sale
3                 Monthly Report
4                         Survey
..                           ...
195                Policy Update
196                Order Shipped
197            Weekly Newsletter
198              Payment Overdue
199          Promotion: Big Sale

                                                  body priority  triage_label  \
0    Reminder: The client meeting is scheduled at 1...      low  notify_human
1    Your invoice of INR 25515.09 is due on 2025-12...      low       respond
2    Reminder: The client meeting is scheduled at 1...      low        ignore
3    Hello team, please find the attached weekly re...   medium       respond
4    Hello team, please find the attached weekly re...      low       respond
..                                                 ...      ...           ...
195  Security alert: multiple failed login attempts...      low  notify_human
196  Your order #3828 has been shipped and is expec...   medium       respond
197  Congratulations! You have been selected as a l...   medium        ignore
198  Please complete the mandatory training module ...      low  notify_human
199  Congratulations! You have been selected as a l...      low        ignore

    ideal_intent ideal_tone  \
0        respond    neutral
1        respond    neutral
2        respond    neutral
3        respond     polite
4        respond     polite
..           ...        ...
195       notify     urgent
196      respond     polite
197       ignore    neutral
198       notify     urgent
199       ignore    neutral

                                            clean_text          triage  \
0    reminder: the client meeting is scheduled at 1...  respond_or_act
1    your invoice of inr 25515.09 is due on 2025-12...    notify_human
2    reminder: the client meeting is scheduled at 1...  respond_or_act
3    hello team, please find the attached weekly re...  respond_or_act
4    hello team, please find the attached weekly re...  respond_or_act
..                                                 ...             ...
195  security alert: multiple failed login attempts...  respond_or_act
196  your order #3828 has been shipped and is expec...  respond_or_act
197  congratulations! you have been selected as a l...          ignore
198  please complete the mandatory training module ...  respond_or_act
199  congratulations! you have been selected as a l...          ignore

            triage_match predicted_triage
0            \bmeeting\b   respond_or_act
1            \binvoice\b   respond_or_act
2            \bmeeting\b   respond_or_act
3           \battached\b   respond_or_act
4           \battached\b   respond_or_act
..                   ...              ...
195     default_fallback   respond_or_act
196     default_fallback   respond_or_act
197  \bcongratulations\b   respond_or_act
198     default_fallback   respond_or_act
199  \bcongratulations\b   respond_or_act

[200 rows x 12 columns]>

In [16]:
import pandas as pd

df = pd.read_csv("../data/sample_emails_with_triage_200.csv")
df.head()

,id,sender,subject,body,priority,triage_label,ideal_intent,ideal_tone
0,1,[alerts@bank.com](mailto:alerts@bank.com),Password Reset Request,Reminder: The client meeting is scheduled at 1...,low,notify_human,respond,neutral
1,2,[alerts@bank.com](mailto:alerts@bank.com),Congratulations! You've Won,Your invoice of INR 25515.09 is due on 2025-12...,low,respond,respond,neutral
2,3,[no-reply@service.com](mailto:no-reply@service...,Promotion: Big Sale,Reminder: The client meeting is scheduled at 1...,low,ignore,respond,neutral
3,4,[sales@shop.com](mailto:sales@shop.com),Monthly Report,"Hello team, please find the attached weekly re...",medium,respond,respond,polite
4,5,[no-reply@service.com](mailto:no-reply@service...,Survey,"Hello team, please find the attached weekly re...",low,respond,respond,polite

In [17]:
#select 100 test emails
eval_df = df.sample(100, random_state=42)
eval_df = eval_df.reset_index(drop=True)

eval_df.head()

,id,sender,subject,body,priority,triage_label,ideal_intent,ideal_tone
0,96,[no-reply@service.com](mailto:no-reply@service...,Weekly Newsletter,Your order #3634 has been shipped and is expec...,low,ignore,respond,polite
1,16,[news@techblog.com](mailto:news@techblog.com),Payment Overdue,"Hi, don't miss our sale with discounts up to 7...",low,notify_human,ignore,neutral
2,31,[news@techblog.com](mailto:news@techblog.com),Weekly Newsletter,Notice: Your account will be locked unless ver...,high,notify_human,notify,urgent
3,159,[no-reply@service.com](mailto:no-reply@service...,Welcome to Service,Reminder: The client meeting is scheduled at 9...,low,respond,respond,neutral
4,129,[sales@shop.com](mailto:sales@shop.com),Invoice Due,Your order #6464 has been shipped and is expec...,low,respond,respond,polite

In [18]:
df.head()

,id,sender,subject,body,priority,triage_label,ideal_intent,ideal_tone
0,1,[alerts@bank.com](mailto:alerts@bank.com),Password Reset Request,Reminder: The client meeting is scheduled at 1...,low,notify_human,respond,neutral
1,2,[alerts@bank.com](mailto:alerts@bank.com),Congratulations! You've Won,Your invoice of INR 25515.09 is due on 2025-12...,low,respond,respond,neutral
2,3,[no-reply@service.com](mailto:no-reply@service...,Promotion: Big Sale,Reminder: The client meeting is scheduled at 1...,low,ignore,respond,neutral
3,4,[sales@shop.com](mailto:sales@shop.com),Monthly Report,"Hello team, please find the attached weekly re...",medium,respond,respond,polite
4,5,[no-reply@service.com](mailto:no-reply@service...,Survey,"Hello team, please find the attached weekly re...",low,respond,respond,polite

In [19]:
import pandas as pd


data = {
    'id': [1, 2, 3, 4, 5],
    'sender': [
        'alerts@bank.com', 'alerts@bank.com', 'no-reply@service.com',
        'sales@shop.com', 'no-reply@service.com'
    ],
    'subject': [
        'Password Reset Request', "Congratulations! You've Won", 
        'Promotion: Big Sale', 'Monthly Report', 'Survey'
    ],
    'body': [
        'Reminder: The client meeting is scheduled at 1...',
        'Your invoice of INR 25515.09 is due on 2025-12...',
        'Reminder: The client meeting is scheduled at 1...',
        'Hello team, please find the attached weekly re...',
        'Hello team, please find the attached weekly re...'
    ],
    'priority': ['low', 'low', 'low', 'medium', 'low'],
    'triage_label': ['notify_human', 'respond', 'ignore', 'respond', 'respond']
}

In [20]:
df = pd.DataFrame(data)

In [21]:
df['triage_label'] = df['triage_label'].str.strip().str.lower()
df['triage_label'] = df['triage_label'].str.strip().str.lower()

In [22]:

def generate_response(triage):
    if triage == 'notify_human':
        return "This email is important. Please notify or escalate to the human immediately."
    elif triage == 'respond':
        return "Please respond to this email and take the required action."
    elif triage == 'ignore':
        return "No action is required for this email."
    else:
        return "Review the email and take appropriate action."

In [23]:
df['ideal_response'] = df['triage_label'].apply(generate_response)

df[['triage_label', 'ideal_response']].head()

   triage_label                                     ideal_response
0  notify_human  This email is important. Please notify or esca...
1       respond  Please respond to this email and take the requ...
2        ignore              No action is required for this email.
3       respond  Please respond to this email and take the requ...
4       respond  Please respond to this email and take the requ...

In [24]:
df.head()

,id,sender,subject,body,priority,triage_label,ideal_response
0,1,alerts@bank.com,Password Reset Request,Reminder: The client meeting is scheduled at 1...,low,notify_human,This email is important. Please notify or esca...
1,2,alerts@bank.com,Congratulations! You've Won,Your invoice of INR 25515.09 is due on 2025-12...,low,respond,Please respond to this email and take the requ...
2,3,no-reply@service.com,Promotion: Big Sale,Reminder: The client meeting is scheduled at 1...,low,ignore,No action is required for this email.
3,4,sales@shop.com,Monthly Report,"Hello team, please find the attached weekly re...",medium,respond,Please respond to this email and take the requ...
4,5,no-reply@service.com,Survey,"Hello team, please find the attached weekly re...",low,respond,Please respond to this email and take the requ...

In [25]:
import pandas as pd

# Load existing CSV
df = pd.read_csv("../data/email_evaluation_dataset_arbind.csv")
print("Loaded emails:", len(df))

# Create new evaluation DataFrame
eval_df = pd.DataFrame({
    "email_text": df["email_text"],
    "expected_action": df["expected_action"],
    "expected_tone": df["expected_tone"]
})

# Save the new CSV
output_path = "../data/email_evaluation_dataset_arbind.csv"
eval_df.to_csv(output_path, index=False)

print("New evaluation dataset created with", len(eval_df), "emails")
print("Saved at:", output_path)

Loaded emails: 98
New evaluation dataset created with 98 emails
Saved at: ../data/email_evaluation_dataset_arbind.csv

In [26]:
df.head()

,email_text,expected_action,expected_tone
0,Reminder: Team meeting scheduled tomorrow at 1...,respond,polite
1,Your electricity bill payment is overdue. Plea...,notify,urgent
2,Congratulations! You have won a gift voucher. ...,ignore,neutral
3,Please find attached the internship offer lett...,respond,polite
4,System alert: Multiple failed login attempts d...,notify,urgent