In [2]:
import pandas as pd

df = pd.read_csv("../data/email_evaluation_dataset_arbind.csv")
df.head()

,email_text,expected_action,expected_tone
0,Reminder: Team meeting scheduled tomorrow at 1...,respond,polite
1,Your electricity bill payment is overdue. Plea...,notify,urgent
2,Congratulations! You have won a gift voucher. ...,ignore,neutral
3,Please find attached the internship offer lett...,respond,polite
4,System alert: Multiple failed login attempts d...,notify,urgent

In [4]:
def classify_email(row):
    action = str(row['expected_action']).lower()
    tone = str(row['expected_tone']).lower()
    
    if action == "notify" or tone == "urgent":
        return "Important: Notify immediately"
    elif action == "ignore" or tone == "polite":
        return "Polite: No action needed"
    else:
        return "Normal: Needs a response"

df['Classification'] = df.apply(classify_email, axis=1)
df.head()

,email_text,expected_action,expected_tone,Classification
0,Reminder: Team meeting scheduled tomorrow at 1...,respond,polite,Polite: No action needed
1,Your electricity bill payment is overdue. Plea...,notify,urgent,Important: Notify immediately
2,Congratulations! You have won a gift voucher. ...,ignore,neutral,Polite: No action needed
3,Please find attached the internship offer lett...,respond,polite,Polite: No action needed
4,System alert: Multiple failed login attempts d...,notify,urgent,Important: Notify immediately