In [3]:
import os
os.chdir(r"C:\Users\Prana\OneDrive\Documents\GitHub\infosys-langgraph-email-assistant-group2")
print(os.getcwd())

C:\Users\Prana\OneDrive\Documents\GitHub\infosys-langgraph-email-assistant-group2

In [4]:
import pandas as pd
df=pd.read_csv('data/milestone1_pranaya.csv')
df.head()

,id,sender,subject,body,priority,triage_label,clean_text,triage,triage_match,predicted_triage
0,1,alerts@bank.com,Password Reset Request,Reminder: The client meeting is scheduled at 1...,low,notify_human,reminder: the client meeting is scheduled at 1...,respond_or_act,\bmeeting\b,respond_or_act
1,2,alerts@bank.com,Congratulations! You've Won,Your invoice of INR 25515.09 is due on 2025-12...,low,respond,your invoice of inr 25515.09 is due on 2025-12...,notify_human,\binvoice\b,respond_or_act
2,3,no-reply@service.com,Promotion: Big Sale,Reminder: The client meeting is scheduled at 1...,low,ignore,reminder: the client meeting is scheduled at 1...,respond_or_act,\bmeeting\b,respond_or_act
3,4,sales@shop.com,Monthly Report,"Hello team, please find the attached weekly re...",medium,respond,"hello team, please find the attached weekly re...",respond_or_act,\battached\b,respond_or_act
4,5,no-reply@service.com,Survey,"Hello team, please find the attached weekly re...",low,respond,"hello team, please find the attached weekly re...",respond_or_act,\battached\b,respond_or_act

In [5]:
df=pd.read_csv('data/milestone1_pranaya.csv')
df.head()

,id,sender,subject,body,priority,triage_label,clean_text,triage,triage_match,predicted_triage
0,1,alerts@bank.com,Password Reset Request,Reminder: The client meeting is scheduled at 1...,low,notify_human,reminder: the client meeting is scheduled at 1...,respond_or_act,\bmeeting\b,respond_or_act
1,2,alerts@bank.com,Congratulations! You've Won,Your invoice of INR 25515.09 is due on 2025-12...,low,respond,your invoice of inr 25515.09 is due on 2025-12...,notify_human,\binvoice\b,respond_or_act
2,3,no-reply@service.com,Promotion: Big Sale,Reminder: The client meeting is scheduled at 1...,low,ignore,reminder: the client meeting is scheduled at 1...,respond_or_act,\bmeeting\b,respond_or_act
3,4,sales@shop.com,Monthly Report,"Hello team, please find the attached weekly re...",medium,respond,"hello team, please find the attached weekly re...",respond_or_act,\battached\b,respond_or_act
4,5,no-reply@service.com,Survey,"Hello team, please find the attached weekly re...",low,respond,"hello team, please find the attached weekly re...",respond_or_act,\battached\b,respond_or_act

In [6]:
def triage_rule(text):
    text = text.lower()

    if "refund" in text or "urgent" in text or "password" in text:
        return "notify_human"

    if "newsletter" in text or "promotion" in text:
        return "ignore"

    return "respond_or_act"

df['triage'] = df['clean_text'].apply(triage_rule)
df[['body', 'triage']].head()

                                                body          triage
0  Reminder: The client meeting is scheduled at 1...  respond_or_act
1  Your invoice of INR 25515.09 is due on 2025-12...  respond_or_act
2  Reminder: The client meeting is scheduled at 1...  respond_or_act
3  Hello team, please find the attached weekly re...  respond_or_act
4  Hello team, please find the attached weekly re...  respond_or_act

In [7]:
df['predicted_triage'] = df['clean_text'].apply(triage_rule)
df[['body','predicted_triage']].head()

                                                body predicted_triage
0  Reminder: The client meeting is scheduled at 1...   respond_or_act
1  Your invoice of INR 25515.09 is due on 2025-12...   respond_or_act
2  Reminder: The client meeting is scheduled at 1...   respond_or_act
3  Hello team, please find the attached weekly re...   respond_or_act
4  Hello team, please find the attached weekly re...   respond_or_act

In [8]:
df = pd.read_csv('data/milestone1_pranaya.csv')
#select 100 test emails
eval_df = df.sample(n=100, random_state=42)
eval_df = eval_df.reset_index(drop=True)
eval_df.head()

,id,sender,subject,body,priority,triage_label,clean_text,triage,triage_match,predicted_triage
0,96,no-reply@service.com,Weekly Newsletter,Your order #3634 has been shipped and is expec...,low,ignore,your order #3634 has been shipped and is expec...,respond_or_act,default_fallback,respond_or_act
1,16,news@techblog.com,Payment Overdue,"Hi, don't miss our sale with discounts up to 7...",low,notify_human,"hi, don't miss our sale with discounts up to 7...",ignore,\bsale\b,respond_or_act
2,31,news@techblog.com,Weekly Newsletter,Notice: Your account will be locked unless ver...,high,notify_human,notice: your account will be locked unless ver...,respond_or_act,default_fallback,respond_or_act
3,159,no-reply@service.com,Welcome to Service,Reminder: The client meeting is scheduled at 9...,low,respond,reminder: the client meeting is scheduled at 9...,respond_or_act,\bmeeting\b,respond_or_act
4,129,sales@shop.com,Invoice Due,Your order #6464 has been shipped and is expec...,low,respond,your order #6464 has been shipped and is expec...,respond_or_act,default_fallback,respond_or_act

In [9]:
#creating an column of ideal_response
def ideal_response_logic(label):
    if label == 'ignore':
        return 'No action needed'
    elif label == 'respond':
        return 'Send a reply'
    elif label == 'respond_or_act':
        return 'Respond and take required action'
    elif label == 'notify_human':
        return 'Escalate to human'
    else:
        return 'Manual review required'

In [10]:
df['ideal_response'] = df['triage_label'].apply(ideal_response_logic)
df[['triage_label', 'ideal_response']].head()

   triage_label     ideal_response
0  notify_human  Escalate to human
1       respond       Send a reply
2        ignore   No action needed
3       respond       Send a reply
4       respond       Send a reply

In [11]:
#loading the dataset
df = pd.read_csv("data/email_evaluation_dataset_pranaya.csv")
df.head()

,id,email_text,expected_action,expected_tone
0,1,You are receiving this email as part of our re...,ignore,neutral
1,2,"Dear Meera, just a quick reminder that we have...",respond,polite
2,3,This is our monthly newsletter highlighting re...,ignore,neutral
3,4,"Hello Meera, this is to inform you that your a...",notify,polite
4,5,"Hello Meera, this is a follow-up regarding the...",respond,urgent

In [22]:
def email_assistant(email_text):
    text = email_text.lower()
    if "invoice" in text:
        return "respond", "urgent"
    if "meeting" in text:
        return "respond", "polite"
    if "internship" in text:
        return "notify", "polite"
    if "query" in text:
        return "respond", "neutral"
    if "newsletter" in text:
        return "ignore", "neutral"
    return "ignore", "neutral"

In [23]:
#tuples splitting into columns
import pandas as pd
df[['predicted_action', 'predicted_tone']] = df['email_text'].apply(
    lambda x: pd.Series(email_assistant(x))
)

In [24]:
df[['email_text',
    'expected_action', 'predicted_action',
    'expected_tone', 'predicted_tone']].head()

,email_text,expected_action,predicted_action,expected_tone,predicted_tone
0,You are receiving this email as part of our re...,ignore,ignore,neutral,neutral
1,"Dear Meera, just a quick reminder that we have...",respond,respond,polite,polite
2,This is our monthly newsletter highlighting re...,ignore,ignore,neutral,neutral
3,"Hello Meera, this is to inform you that your a...",notify,ignore,polite,neutral
4,"Hello Meera, this is a follow-up regarding the...",respond,respond,urgent,urgent

In [25]:
#accuracy calculation
action_accuracy = (df['expected_action'] == df['predicted_action']).mean()*100
tone_accuracy = (df['expected_tone'] == df['predicted_tone']).mean()*100
print(f"Action accuracy (%): {action_accuracy:.2f}")
print(f"Tone accuracy (%): {tone_accuracy:.2f}")

Action accuracy (%): 80.00
Tone accuracy (%): 89.00

In [26]:
#Perform error analysis
action_errors = df[df['expected_action'] != df['predicted_action']]
tone_errors = df[df['expected_tone'] != df['predicted_tone']]
action_errors[
    ['email_text', 'expected_action', 'predicted_action']
]
tone_errors[
    ['email_text', 'expected_tone', 'predicted_tone']
]

,email_text,expected_tone,predicted_tone
3,"Hello Meera, this is to inform you that your a...",polite,neutral
5,"Hello Alex, this is to inform you that your ac...",polite,neutral
29,"Hello Sam, this is to inform you that your aca...",polite,neutral
51,"Hello Aditi, this is to inform you that your a...",polite,neutral
52,"Hello Meera, this is to inform you that your a...",polite,neutral
58,"Hello Sam, this is to inform you that your aca...",polite,neutral
62,"Hello Aditi, this is to inform you that your a...",polite,neutral
74,"Hello Pranaya, this is to inform you that your...",polite,neutral
85,"Hello Pranaya, this is to inform you that your...",polite,neutral
91,"Hello Rohit, this is to inform you that your a...",polite,neutral
96,"Hello Kiran, this is to inform you that your a...",polite,neutral

In [27]:
df.to_csv("data/milestone2_output_pranaya.csv", index=False)