In [1]:
import pandas as pd
df =pd.read_csv("../data/milestone1_bhumika.csv")
df.head()

,id,sender,subject,body,priority,triage_label,Clean_text,triage_prediction
0,1,alerts@bank.com,Password Reset Request,Reminder: The client meeting is scheduled at 1...,low,notify_human,reminder the client meeting is scheduled at 10...,respond_or_act
1,2,alerts@bank.com,Congratulations! You've Won,Your invoice of INR 25515.09 is due on 2025-12...,low,respond,your invoice of inr 2551509 is due on 20251212...,respond_or_act
2,3,no-reply@service.com,Promotion: Big Sale,Reminder: The client meeting is scheduled at 1...,low,ignore,reminder the client meeting is scheduled at 11...,respond_or_act
3,4,sales@shop.com,Monthly Report,"Hello team, please find the attached weekly re...",medium,respond,hello team please find the attached weekly rep...,respond_or_act
4,5,no-reply@service.com,Survey,"Hello team, please find the attached weekly re...",low,respond,hello team please find the attached weekly rep...,respond_or_act

In [2]:
df.shape

(200, 8)

In [3]:
import os

print(os.path.abspath("../data/sample_emails_with_triage_200.csv"))

c:\Users\PC-LENOVO\Desktop\infosys\infosys-langgraph-email-assistant-group2\data\sample_emails_with_triage_200.csv

In [8]:
#select 100 test emails
eval_df = df.sample(100, random_state=42)
eval_df = eval_df.reset_index(drop=True)

eval_df.head()

,id,sender,subject,body,priority,triage_label,Clean_text,triage_prediction
0,96,no-reply@service.com,Weekly Newsletter,Your order #3634 has been shipped and is expec...,low,ignore,your order 3634 has been shipped and is expect...,respond_or_act
1,16,news@techblog.com,Payment Overdue,"Hi, don't miss our sale with discounts up to 7...",low,notify_human,hi dont miss our sale with discounts up to 70 ...,respond_or_act
2,31,news@techblog.com,Weekly Newsletter,Notice: Your account will be locked unless ver...,high,notify_human,notice your account will be locked unless veri...,respond_or_act
3,159,no-reply@service.com,Welcome to Service,Reminder: The client meeting is scheduled at 9...,low,respond,reminder the client meeting is scheduled at 93...,respond_or_act
4,129,sales@shop.com,Invoice Due,Your order #6464 has been shipped and is expec...,low,respond,your order 6464 has been shipped and is expect...,respond_or_act

In [10]:

df.head()

,id,sender,subject,body,priority,triage_label,Clean_text,triage_prediction
0,1,alerts@bank.com,Password Reset Request,Reminder: The client meeting is scheduled at 1...,low,notify_human,reminder the client meeting is scheduled at 10...,respond_or_act
1,2,alerts@bank.com,Congratulations! You've Won,Your invoice of INR 25515.09 is due on 2025-12...,low,respond,your invoice of inr 2551509 is due on 20251212...,respond_or_act
2,3,no-reply@service.com,Promotion: Big Sale,Reminder: The client meeting is scheduled at 1...,low,ignore,reminder the client meeting is scheduled at 11...,respond_or_act
3,4,sales@shop.com,Monthly Report,"Hello team, please find the attached weekly re...",medium,respond,hello team please find the attached weekly rep...,respond_or_act
4,5,no-reply@service.com,Survey,"Hello team, please find the attached weekly re...",low,respond,hello team please find the attached weekly rep...,respond_or_act

In [11]:

import pandas as pd


data = {
    'id': [1, 2, 3, 4, 5],
    'sender': [
        'alerts@bank.com', 'alerts@bank.com', 'no-reply@service.com',
        'sales@shop.com', 'no-reply@service.com'
    ],
    'subject': [
        'Password Reset Request', "Congratulations! You've Won", 
        'Promotion: Big Sale', 'Monthly Report', 'Survey'
    ],
    'body': [
        'Reminder: The client meeting is scheduled at 1...',
        'Your invoice of INR 25515.09 is due on 2025-12...',
        'Reminder: The client meeting is scheduled at 1...',
        'Hello team, please find the attached weekly re...',
        'Hello team, please find the attached weekly re...'
    ],
    'priority': ['low', 'low', 'low', 'medium', 'low'],
    'triage_label': ['notify_human', 'respond', 'ignore', 'respond', 'respond']
}

In [12]:

df = pd.DataFrame(data)

In [13]:

def generate_response(triage):
    if triage == 'notify_human':
        return "This email is important. Please notify or escalate to the human immediately."
    elif triage == 'respond':
        return "Please respond to this email and take the required action."
    elif triage == 'ignore':
        return "No action is required for this email."
    else:
        return "Review the email and take appropriate action."

In [14]:
df['ideal_response'] = df['triage_label'].apply(generate_response)

df[['triage_label', 'ideal_response']].head()

   triage_label                                     ideal_response
0  notify_human  This email is important. Please notify or esca...
1       respond  Please respond to this email and take the requ...
2        ignore              No action is required for this email.
3       respond  Please respond to this email and take the requ...
4       respond  Please respond to this email and take the requ...

In [15]:

df.head()

,id,sender,subject,body,priority,triage_label,ideal_response
0,1,alerts@bank.com,Password Reset Request,Reminder: The client meeting is scheduled at 1...,low,notify_human,This email is important. Please notify or esca...
1,2,alerts@bank.com,Congratulations! You've Won,Your invoice of INR 25515.09 is due on 2025-12...,low,respond,Please respond to this email and take the requ...
2,3,no-reply@service.com,Promotion: Big Sale,Reminder: The client meeting is scheduled at 1...,low,ignore,No action is required for this email.
3,4,sales@shop.com,Monthly Report,"Hello team, please find the attached weekly re...",medium,respond,Please respond to this email and take the requ...
4,5,no-reply@service.com,Survey,"Hello team, please find the attached weekly re...",low,respond,Please respond to this email and take the requ...

In [16]:
import pandas as pd

# Load existing CSV
df = pd.read_csv("../data/email_evaluation_dataset_bhumika.csv")
print("Loaded emails:", len(df))

# Create new evaluation DataFrame
eval_df = pd.DataFrame({
    "email_text": df["email_text"],
    "expected_action": df["expected_action"],
    "expected_tone": df["expected_tone"]
})

# Save the new CSV
output_path = "../data/email_evaluation_dataset_bhumika.csv"
eval_df.to_csv(output_path, index=False)

print("New evaluation dataset created with", len(eval_df), "emails")
print("Saved at:", output_path)

Loaded emails: 98
New evaluation dataset created with 98 emails
Saved at: ../data/email_evaluation_dataset_bhumika.csv