In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/email_evaluation_dataset_Nikhitha.csv")
df.head()

,email_text,expected_action,expected_tone
0,Please attend the project status meeting tomor...,respond,polite
1,Your internship completion certificate is read...,respond,polite
2,Kindly submit your assignment by end of day today,respond,neutral
3,This is a reminder to clear the pending invoic...,respond,urgent
4,Thank you for applying. We will get back to yo...,respond,polite

In [3]:
def email_assistant(text):
    t = str(text).lower()
    
    if any(k in t for k in ['invoice','payment','due','meeting','submit','confirm']):
        action = 'respond'
        tone = 'polite'
    elif any(k in t for k in ['password','security','alert','unauthorized','suspicious']):
        action = 'notify'
        tone = 'urgent'
    else:
        action = 'ignore'
        tone = 'neutral'
        
    return action, tone

In [4]:
df[['predicted_action','predicted_tone']] = df['email_text'].apply(
    lambda x: pd.Series(email_assistant(x))
)

df.head()

,email_text,expected_action,expected_tone,predicted_action,predicted_tone
0,Please attend the project status meeting tomor...,respond,polite,respond,polite
1,Your internship completion certificate is read...,respond,polite,ignore,neutral
2,Kindly submit your assignment by end of day today,respond,neutral,respond,polite
3,This is a reminder to clear the pending invoic...,respond,urgent,respond,polite
4,Thank you for applying. We will get back to yo...,respond,polite,ignore,neutral

In [5]:
df['action_correct'] = df['predicted_action'] == df['expected_action']
df['tone_correct'] = df['predicted_tone'] == df['expected_tone']

df.head()

,email_text,expected_action,expected_tone,predicted_action,predicted_tone,action_correct,tone_correct
0,Please attend the project status meeting tomor...,respond,polite,respond,polite,True,True
1,Your internship completion certificate is read...,respond,polite,ignore,neutral,False,False
2,Kindly submit your assignment by end of day today,respond,neutral,respond,polite,True,False
3,This is a reminder to clear the pending invoic...,respond,urgent,respond,polite,True,False
4,Thank you for applying. We will get back to yo...,respond,polite,ignore,neutral,False,False

In [6]:
action_accuracy = df['action_correct'].mean() * 100
tone_accuracy = df['tone_correct'].mean() * 100

action_accuracy, tone_accuracy

(np.float64(60.0), np.float64(65.0))

In [7]:
errors = df[df['action_correct'] == False][
    ['email_text','expected_action','predicted_action']
]

errors.head(10)

,email_text,expected_action,predicted_action
1,Your internship completion certificate is read...,respond,ignore
4,Thank you for applying. We will get back to yo...,respond,ignore
13,The internship orientation session will be hel...,respond,ignore
14,Kindly review the attached document and share ...,respond,ignore
15,Your library book return date has been extended,respond,ignore
16,Please update your contact details in the stud...,respond,ignore
17,This is a final reminder to complete your cour...,respond,ignore
18,Your request for leave has been approved,respond,ignore
19,The exam schedule for next semester has been r...,respond,ignore
29,Urgent notice: multiple failed login attempts ...,notify,ignore

In [8]:
df.to_csv("../data/milestone2_output_Nikhitha.csv", index=False)

In [1]:
eval_df = df.merge(pred_df, on="id")

eval_df["score"] = (
    (eval_df["predicted_intent"] == eval_df["ideal_intent"]).astype(int) +
    (eval_df["predicted_tone"] == eval_df["ideal_tone"]).astype(int)
)

accuracy = (eval_df["score"].sum() / (len(eval_df) * 2)) * 100
accuracy

NameError: name 'df' is not defined

import pandas as pd

df = pd.read_csv("../data/sample_emails_with_triage_200.csv")
df.head()

In [2]:
import pandas as pd

df = pd.read_csv("../data/sample_emails_with_triage_200.csv")
df.head()

,id,sender,subject,body,priority,triage_label,clean_text,triage,ideal_intent,ideal_tone
0,1,alerts@bank.com,Password Reset Request,Reminder: The client meeting is scheduled at 1...,low,notify_human,NaN,NaN,NaN,NaN
1,2,alerts@bank.com,Congratulations! You've Won,Your invoice of INR 25515.09 is due on 2025-12...,low,respond,NaN,NaN,NaN,NaN
2,3,no-reply@service.com,Promotion: Big Sale,Reminder: The client meeting is scheduled at 1...,low,ignore,NaN,NaN,NaN,NaN
3,4,sales@shop.com,Monthly Report,"Hello team, please find the attached weekly re...",medium,respond,NaN,NaN,NaN,NaN
4,5,no-reply@service.com,Survey,"Hello team, please find the attached weekly re...",low,respond,NaN,NaN,NaN,NaN

In [3]:
def email_assistant(email_text):
    text = str(email_text).lower()
    if "urgent" in text or "password" in text or "deadline" in text:
        return "notify", "urgent"
    elif "thank you" in text or "thanks" in text:
        return "ignore", "polite"
    else:
        return "respond", "neutral"

In [4]:
predictions = []

for _, row in df.iterrows():
    action, tone = email_assistant(row["body"])
    predictions.append({
        "id": row["id"],
        "predicted_intent": action,
        "predicted_tone": tone
    })

pred_df = pd.DataFrame(predictions)
pred_df.head()

   id predicted_intent predicted_tone
0   1          respond        neutral
1   2          respond        neutral
2   3          respond        neutral
3   4          respond        neutral
4   5          respond        neutral

In [5]:
predictions = []

for _, row in df.iterrows():
    action, tone = email_assistant(row["body"])
    predictions.append({
        "id": row["id"],
        "predicted_intent": action,
        "predicted_tone": tone
    })

pred_df = pd.DataFrame(predictions)
pred_df.head()

   id predicted_intent predicted_tone
0   1          respond        neutral
1   2          respond        neutral
2   3          respond        neutral
3   4          respond        neutral
4   5          respond        neutral

In [6]:
import pandas as pd

df = pd.read_csv("../data/sample_emails_with_triage_200.csv")
df.head()

,id,sender,subject,body,priority,triage_label,clean_text,triage,ideal_intent,ideal_tone
0,1,alerts@bank.com,Password Reset Request,Reminder: The client meeting is scheduled at 1...,low,notify_human,NaN,NaN,NaN,NaN
1,2,alerts@bank.com,Congratulations! You've Won,Your invoice of INR 25515.09 is due on 2025-12...,low,respond,NaN,NaN,NaN,NaN
2,3,no-reply@service.com,Promotion: Big Sale,Reminder: The client meeting is scheduled at 1...,low,ignore,NaN,NaN,NaN,NaN
3,4,sales@shop.com,Monthly Report,"Hello team, please find the attached weekly re...",medium,respond,NaN,NaN,NaN,NaN
4,5,no-reply@service.com,Survey,"Hello team, please find the attached weekly re...",low,respond,NaN,NaN,NaN,NaN

In [7]:
def email_assistant(email_text):
    text = str(email_text).lower()
    if "urgent" in text or "password" in text or "deadline" in text:
        return "notify", "urgent"
    elif "thank you" in text or "thanks" in text:
        return "ignore", "polite"
    else:
        return "respond", "neutral"

In [8]:
predictions = []

for _, row in df.iterrows():
    action, tone = email_assistant(row["body"])
    predictions.append({
        "id": row["id"],
        "predicted_intent": action,
        "predicted_tone": tone
    })

pred_df = pd.DataFrame(predictions)
pred_df.head()

   id predicted_intent predicted_tone
0   1          respond        neutral
1   2          respond        neutral
2   3          respond        neutral
3   4          respond        neutral
4   5          respond        neutral

In [9]:
eval_df = df.merge(pred_df, on="id")

eval_df["score"] = (
    (eval_df["predicted_intent"] == eval_df["ideal_intent"]).astype(int) +
    (eval_df["predicted_tone"] == eval_df["ideal_tone"]).astype(int)
)

accuracy = (eval_df["score"].sum() / (len(eval_df) * 2)) * 100

print("Accuracy:", accuracy)

Accuracy: 0.0

In [11]:
eval_df["score"] = (
    (eval_df["predicted_intent"] == eval_df["ideal_intent"]).astype(int) +
    (eval_df["predicted_tone"] == eval_df["ideal_tone"]).astype(int)
)

In [12]:
accuracy = (eval_df["score"].sum() / (len(eval_df) * 2)) * 100
print("Accuracy:", accuracy)

Accuracy: 0.0

In [1]:
import pandas as pd

df = pd.read_csv("../data/sample_emails_with_triage_200.csv")

email_eval_df = df[["id", "body", "ideal_intent", "ideal_tone"]]

email_eval_df.to_csv(
    "../data/email_evaluation_dataset_Nikhitha.csv",
    index=False
)

print("email_evaluation_dataset_Nikhitha.csv created")

KeyError: "['ideal_intent', 'ideal_tone'] not in index"

In [2]:
df.columns

Index(['id', 'sender', 'subject', 'body', 'priority', 'triage_label'], dtype='object')

In [3]:
def add_ground_truth(text):
    text = str(text).lower()

    if any(w in text for w in ["submit", "deadline", "meeting", "reminder", "asap", "eod"]):
        return "respond", "urgent"
    elif any(w in text for w in ["thank you", "thanks"]):
        return "ignore", "polite"
    elif any(w in text for w in ["please", "can you", "could you", "review", "confirm"]):
        return "respond", "polite"
    else:
        return "ignore", "neutral"


df[["ideal_intent", "ideal_tone"]] = df["body"].apply(
    lambda x: pd.Series(add_ground_truth(x))
)

In [4]:
email_eval_df = df[["id", "body", "ideal_intent", "ideal_tone"]]

email_eval_df.to_csv(
    "../data/email_evaluation_dataset_Nikhitha.csv",
    index=False
)

print("email_evaluation_dataset_Nikhitha.csv created")

email_evaluation_dataset_Nikhitha.csv created

In [5]:
pd.read_csv("../data/email_evaluation_dataset_Nikhitha.csv").head()

,id,body,ideal_intent,ideal_tone
0,1,Reminder: The client meeting is scheduled at 1...,respond,urgent
1,2,Your invoice of INR 25515.09 is due on 2025-12...,respond,polite
2,3,Reminder: The client meeting is scheduled at 1...,respond,urgent
3,4,"Hello team, please find the attached weekly re...",respond,polite
4,5,"Hello team, please find the attached weekly re...",respond,polite