In [15]:
#virtual environment setup code
import os
os.chdir(r"C:\Users\Prana\OneDrive\Documents\GitHub\infosys-langgraph-email-assistant-group2")
print(os.getcwd())

C:\Users\Prana\OneDrive\Documents\GitHub\infosys-langgraph-email-assistant-group2

In [12]:
# Install necessary packages
!pip install pandas nltk langchain-google-genai langsmith
import pandas as pd
import nltk #natural language toolkit
from typing import Dict, List  # for type hints
import re
from langchain_google_genai import ChatGoogleGenerativeAI
from langsmith import traceable
nltk.download('punkt') #tokenizer data
nltk.download('stopwords') #stopwords data

Requirement already satisfied: pandas in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (2.3.3)
Requirement already satisfied: nltk in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (3.9.2)
Requirement already satisfied: langchain-google-genai in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (4.1.3)
Requirement already satisfied: langsmith in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (0.6.2)
Requirement already satisfied: numpy>=1.23.2 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from pandas) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: click in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: filetype<2.0.0,>=1.2.0 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from langchain-google-genai) (1.2.0)
Requirement already satisfied: google-genai<2.0.0,>=1.56.0 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from langchain-google-genai) (1.57.0)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.5 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from langchain-google-genai) (1.2.7)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from langchain-google-genai) (2.12.5)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from google-genai<2.0.0,>=1.56.0->langchain-google-genai) (4.12.1)
Requirement already satisfied: google-auth<3.0.0,>=2.46.0 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from google-auth[requests]<3.0.0,>=2.46.0->google-genai<2.0.0,>=1.56.0->langchain-google-genai) (2.47.0)
Requirement already satisfied: httpx<1.0.0,>=0.28.1 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from google-genai<2.0.0,>=1.56.0->langchain-google-genai) (0.28.1)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from google-genai<2.0.0,>=1.56.0->langchain-google-genai) (2.32.5)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from google-genai<2.0.0,>=1.56.0->langchain-google-genai) (9.1.2)
Requirement already satisfied: websockets<15.1.0,>=13.0.0 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from google-genai<2.0.0,>=1.56.0->langchain-google-genai) (15.0.1)
Requirement already satisfied: typing-extensions<5.0.0,>=4.11.0 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from google-genai<2.0.0,>=1.56.0->langchain-google-genai) (4.15.0)
Requirement already satisfied: distro<2,>=1.7.0 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from google-genai<2.0.0,>=1.56.0->langchain-google-genai) (1.9.0)
Requirement already satisfied: sniffio in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from google-genai<2.0.0,>=1.56.0->langchain-google-genai) (1.3.1)
Requirement already satisfied: idna>=2.8 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from anyio<5.0.0,>=4.8.0->google-genai<2.0.0,>=1.56.0->langchain-google-genai) (3.11)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from google-auth<3.0.0,>=2.46.0->google-auth[requests]<3.0.0,>=2.46.0->google-genai<2.0.0,>=1.56.0->langchain-google-genai) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from google-auth<3.0.0,>=2.46.0->google-auth[requests]<3.0.0,>=2.46.0->google-genai<2.0.0,>=1.56.0->langchain-google-genai) (4.9.1)
Requirement already satisfied: certifi in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from httpx<1.0.0,>=0.28.1->google-genai<2.0.0,>=1.56.0->langchain-google-genai) (2026.1.4)
Requirement already satisfied: httpcore==1.* in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from httpx<1.0.0,>=0.28.1->google-genai<2.0.0,>=1.56.0->langchain-google-genai) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai<2.0.0,>=1.56.0->langchain-google-genai) (0.16.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from langchain-core<2.0.0,>=1.2.5->langchain-google-genai) (1.33)
Requirement already satisfied: packaging<26.0.0,>=23.2.0 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from langchain-core<2.0.0,>=1.2.5->langchain-google-genai) (25.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from langchain-core<2.0.0,>=1.2.5->langchain-google-genai) (6.0.3)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from langchain-core<2.0.0,>=1.2.5->langchain-google-genai) (0.13.0)
Requirement already satisfied: orjson>=3.9.14 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from langsmith) (3.11.5)
Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from langsmith) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from langsmith) (0.25.0)
Requirement already satisfied: jsonpointer>=1.9 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.5->langchain-google-genai) (3.0.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from pydantic<3.0.0,>=2.0.0->langchain-google-genai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from pydantic<3.0.0,>=2.0.0->langchain-google-genai) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from pydantic<3.0.0,>=2.0.0->langchain-google-genai) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from requests<3.0.0,>=2.28.1->google-genai<2.0.0,>=1.56.0->langchain-google-genai) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from requests<3.0.0,>=2.28.1->google-genai<2.0.0,>=1.56.0->langchain-google-genai) (2.6.3)
Requirement already satisfied: pyasn1>=0.1.3 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from rsa<5,>=3.1.4->google-auth<3.0.0,>=2.46.0->google-auth[requests]<3.0.0,>=2.46.0->google-genai<2.0.0,>=1.56.0->langchain-google-genai) (0.6.1)
Requirement already satisfied: six>=1.5 in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: colorama in c:\users\prana\onedrive\documents\github\infosys-langgraph-email-assistant-group2\.venv\lib\site-packages (from click->nltk) (0.4.6)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Prana\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Prana\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [13]:
import os
os.environ["GOOGLE_API_KEY"] = "AIzaSyAvemY051aREw5JqXXwpU4xuHJLYu7gYFI"

In [1]:
import os
from dotenv import load_dotenv
load_dotenv()

False

In [8]:
from langchain_google_genai import ChatGoogleGenerativeAI
llm=ChatGoogleGenerativeAI(model="gemini-2.5-flash",
                           temperature=0,)
response = llm.invoke("Hello from Infosys email agent")
print(response.content)

Hello! It's great to hear from an Infosys email agent.

How can I assist you today? What can I do for you?

In [17]:
#loading the dataset
df = pd.read_csv("data/sample_emails_with_triage_200.csv")
df.head()

,id,sender,subject,body,priority,triage_label,ideal_intent,ideal_tone
0,1,alerts@bank.com,Password Reset Request,Reminder: The client meeting is scheduled at 1...,low,notify_human,respond,neutral
1,2,alerts@bank.com,Congratulations! You've Won,Your invoice of INR 25515.09 is due on 2025-12...,low,respond,notify,urgent
2,3,no-reply@service.com,Promotion: Big Sale,Reminder: The client meeting is scheduled at 1...,low,ignore,respond,neutral
3,4,sales@shop.com,Monthly Report,"Hello team, please find the attached weekly re...",medium,respond,respond,neutral
4,5,no-reply@service.com,Survey,"Hello team, please find the attached weekly re...",low,respond,respond,neutral

In [4]:
import pandas as pd #data manipulation library

In [5]:
import numpy as np #numerical computing library

In [6]:
import re #regular expressions library

In [7]:
#loading the dataset
df = pd.read_csv("data/sample_emails_with_triage_200.csv")
df.head()

,id,sender,subject,body,priority,triage_label,ideal_intent,ideal_tone
0,1,alerts@bank.com,Password Reset Request,Reminder: The client meeting is scheduled at 1...,low,notify_human,respond,neutral
1,2,alerts@bank.com,Congratulations! You've Won,Your invoice of INR 25515.09 is due on 2025-12...,low,respond,notify,urgent
2,3,no-reply@service.com,Promotion: Big Sale,Reminder: The client meeting is scheduled at 1...,low,ignore,respond,neutral
3,4,sales@shop.com,Monthly Report,"Hello team, please find the attached weekly re...",medium,respond,respond,neutral
4,5,no-reply@service.com,Survey,"Hello team, please find the attached weekly re...",low,respond,respond,neutral

In [8]:
# Data Preprocessing: Cleaning the email body text
df['clean_text'] = (
    df['body']
    .str.lower()
    .str.replace('[^a-zA-Z ]', '', regex=True)
)
df[['body', 'clean_text']].head()

,body,clean_text
0,Reminder: The client meeting is scheduled at 1...,reminder the client meeting is scheduled at t...
1,Your invoice of INR 25515.09 is due on 2025-12...,your invoice of inr is due on please pay to ...
2,Reminder: The client meeting is scheduled at 1...,reminder the client meeting is scheduled at t...
3,"Hello team, please find the attached weekly re...",hello team please find the attached weekly rep...
4,"Hello team, please find the attached weekly re...",hello team please find the attached weekly rep...

In [9]:
# Keyword Extraction: Removing stop words
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
stop_words = set(stopwords.words("english"))
df['keywords'] = df['clean_text'].apply(
    lambda x: [w for w in x.split() if w not in stop_words]
)
df[['clean_text', 'keywords']].head()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Prana\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,clean_text,keywords
0,reminder the client meeting is scheduled at t...,"[reminder, client, meeting, scheduled, tomorro..."
1,your invoice of inr is due on please pay to ...,"[invoice, inr, due, please, pay, avoid, late, ..."
2,reminder the client meeting is scheduled at t...,"[reminder, client, meeting, scheduled, tomorro..."
3,hello team please find the attached weekly rep...,"[hello, team, please, find, attached, weekly, ..."
4,hello team please find the attached weekly rep...,"[hello, team, please, find, attached, weekly, ..."

In [10]:
# Triage Rule Implementation
def triage_rule(text):
    text = text.lower()
    if "refund" in text or "urgent" in text or "password" in text:
        return "notify_human"
    if "newsletter" in text or "promotion" in text:
        return "ignore"
    return "respond_or_act"
df['triage'] = df['clean_text'].apply(triage_rule)
df[['body', 'triage']].head()

                                                body          triage
0  Reminder: The client meeting is scheduled at 1...  respond_or_act
1  Your invoice of INR 25515.09 is due on 2025-12...  respond_or_act
2  Reminder: The client meeting is scheduled at 1...  respond_or_act
3  Hello team, please find the attached weekly re...  respond_or_act
4  Hello team, please find the attached weekly re...  respond_or_act

In [5]:
def triage_email(email):
    propmt = f"""
You are an email triage agent,
Classify this email into one of:
ignore
notify_human
respond
Return ONLY the label.PermissionError
Email:
{email}
"""
    return llm.invoke(propmt).content.strip().lower()

In [19]:
def read_calender() -> str:
    return "No meetings scheduled."
def send_auto_reply() -> str:
    return "Auto-reply sent."

In [24]:
def react_agent(email : Dict) -> Dict:
    though = "Classify email intent using triage rules."
    action = triage_rule(email["body"])
    if action == "notify_human":
        observation = "Human notification needed."
    elif action == "ignore":
        observation = "Email can be ignored."
    else:
        observation = send_auto_reply()
    return {
        "thought": though,
        "action": action,
        "observation": observation
    }

In [4]:
def react_agent(email):
    prompt = f"""
You are an Langrapph AI email assistant.PermissionError
You can reason step by step.
You may use internal tools like calender or CRM if needed.PermissionError
Email:
{email}
Write the final reply to the customer.
"""
    return llm.invoke(prompt).content.strip()

In [6]:
results = []
for _, row in emails.iterrows():
    email = row['email_text']
    triage = triage_email(email)
    if triage == "respond_or_act":
        reaction = react_agent(email)   
    else:
        reply = ""
    results.append({
        "email": email,
        "triage": triage,
        "response": reply
        
    })

NameError: name 'emails' is not defined

In [27]:
results: List[Dict] = []
for _, row in df.iterrows():
    agent_result = react_agent(row)
    results.append({
        "email_id": row["id"],
        "true_triage": row["triage"],
        "predicted_triage": agent_result["action"],
    })
    results_df = pd.DataFrame(results)
results_df.head()

   email_id     true_triage predicted_triage
0         1  respond_or_act   respond_or_act
1         2    notify_human   respond_or_act
2         3  respond_or_act   respond_or_act
3         4  respond_or_act   respond_or_act
4         5  respond_or_act   respond_or_act

In [11]:
# Saving the Processed Data
df.to_csv("data/milestone1_pranaya.csv", index=False)

In [12]:
# 1. Imports + load
import pandas as pd
import re
from IPython.display import display
# adjust path if needed
CSV_PATH = "data/sample_emails_with_triage_200.csv"
df = pd.read_csv(CSV_PATH)
print("Loaded rows:", len(df))
display(df.head())

Loaded rows: 200

,id,sender,subject,body,priority,triage_label,ideal_intent,ideal_tone
0,1,alerts@bank.com,Password Reset Request,Reminder: The client meeting is scheduled at 1...,low,notify_human,respond,neutral
1,2,alerts@bank.com,Congratulations! You've Won,Your invoice of INR 25515.09 is due on 2025-12...,low,respond,notify,urgent
2,3,no-reply@service.com,Promotion: Big Sale,Reminder: The client meeting is scheduled at 1...,low,ignore,respond,neutral
3,4,sales@shop.com,Monthly Report,"Hello team, please find the attached weekly re...",medium,respond,respond,neutral
4,5,no-reply@service.com,Survey,"Hello team, please find the attached weekly re...",low,respond,respond,neutral

In [13]:
# 2. Create a helpful cleaned text column
# Keep words and meaningful tokens (remove only repeated whitespace and control chars)
def make_clean_text(s):
    if not isinstance(s, str):
        return ""
    s = s.strip()
    # normalize spaces and lowercase
    s = re.sub(r'\s+', ' ', s)
    s = s.lower()
    return s
# prefer 'body' column; if not, try 'email_body' or 'subject'
source_col = 'body' if 'body' in df.columns else ('email_body' if 'email_body' in df.columns else 'subject')
df['clean_text'] = df[source_col].astype(str).apply(make_clean_text)
display(df[[source_col,'clean_text']].head())

,body,clean_text
0,Reminder: The client meeting is scheduled at 1...,reminder: the client meeting is scheduled at 1...
1,Your invoice of INR 25515.09 is due on 2025-12...,your invoice of inr 25515.09 is due on 2025-12...
2,Reminder: The client meeting is scheduled at 1...,reminder: the client meeting is scheduled at 1...
3,"Hello team, please find the attached weekly re...","hello team, please find the attached weekly re..."
4,"Hello team, please find the attached weekly re...","hello team, please find the attached weekly re..."

In [14]:
# 3. Debug-friendly triage (regex-based with priority). This returns (label, matched_pattern)
RULES = {
    'notify_human': [
        r'\binvoice\b', r'\bbill\b', r'\bpayment\b', r'\bpassword\b', r'\breset\b',
        r'\bfraud\b', r'\bchargeback\b', r'\bdispute\b', r'\bdenied\b', r'\boverdue\b'
    ],
    'respond_or_act': [
        r'\bmeeting\b', r'\bschedule\b', r'\bscheduled\b', r'\battached\b', r'\battachment\b',
        r'\bplease find\b', r'\bplease review\b', r'\baction required\b', r'\burgent\b', r'\basap\b'
    ],
    'ignore': [
        r'\bunsubscribe\b', r'\bpromotion\b', r'\bsale\b', r'\boffer\b', r'\bnewsletter\b',
        r'\bsurvey\b', r'\bcongratulations\b'
    ]
}
COMPILED = {k:[re.compile(p, flags=re.I) for p in v] for k,v in RULES.items()}
def triage_rule_debug(text):
    if not isinstance(text, str) or text.strip()=="":
        return ('ignore','empty_text')
    for label in ['notify_human','respond_or_act','ignore']:
        for pat in COMPILED[label]:
            if pat.search(text):
                return (label, pat.pattern)
    return ('respond_or_act','default_fallback')
# apply and store both label and matched pattern
df[['triage','triage_match']] = df['clean_text'].apply(lambda t: pd.Series(triage_rule_debug(t)))
print("Triage value counts (advanced):")
print(df['triage'].value_counts())
display(df[['clean_text','triage','triage_match']].head(20))

Triage value counts (advanced):
triage
respond_or_act    127
ignore             42
notify_human       31
Name: count, dtype: int64

,clean_text,triage,triage_match
0,reminder: the client meeting is scheduled at 1...,respond_or_act,\bmeeting\b
1,your invoice of inr 25515.09 is due on 2025-12...,notify_human,\binvoice\b
2,reminder: the client meeting is scheduled at 1...,respond_or_act,\bmeeting\b
3,"hello team, please find the attached weekly re...",respond_or_act,\battached\b
4,"hello team, please find the attached weekly re...",respond_or_act,\battached\b
5,your invoice of inr 38766.88 is due on 2025-12...,notify_human,\binvoice\b
6,congratulations! you have been selected as a l...,ignore,\bcongratulations\b
7,your order #6313 has been shipped and is expec...,respond_or_act,default_fallback
8,"dear user, we detected a login from a new devi...",notify_human,\bpassword\b
9,your invoice of inr 32944.21 is due on 2025-12...,notify_human,\binvoice\b
10,reminder: the client meeting is scheduled at 1...,respond_or_act,\bmeeting\b
11,your order #3621 has been shipped and is expec...,respond_or_act,default_fallback
12,"hello team, please find the attached weekly re...",respond_or_act,\battached\b
13,reminder: the client meeting is scheduled at 1...,respond_or_act,\bmeeting\b
14,please complete the mandatory training module ...,respond_or_act,default_fallback
15,"hi, don't miss our sale with discounts up to 7...",ignore,\bsale\b
16,reminder: the client meeting is scheduled at 1...,respond_or_act,\bmeeting\b
17,"hi, don't miss our sale with discounts up to 7...",ignore,\bsale\b
18,please complete the mandatory training module ...,respond_or_act,default_fallback
19,please complete the mandatory training module ...,respond_or_act,default_fallback

In [15]:
# 5. Diagnostics — use this in live demo to show interns why each label was chosen
print("Top 20 rows with triage reasons:")
display(df[['body','clean_text','triage','triage_match']].head(20))

# show a few sample rows where triage==notify_human for inspection
print("\nSample notify_human rows:")
display(df[df['triage']=='notify_human'][['body','clean_text','triage_match']].head(6))

print("\nSample respond_or_act rows:")
display(df[df['triage']=='respond_or_act'][['body','clean_text','triage_match']].head(6))

print("\nSample ignore rows:")
display(df[df['triage']=='ignore'][['body','clean_text','triage_match']].head(6))

Top 20 rows with triage reasons:

,body,clean_text,triage,triage_match
0,Reminder: The client meeting is scheduled at 1...,reminder: the client meeting is scheduled at 1...,respond_or_act,\bmeeting\b
1,Your invoice of INR 25515.09 is due on 2025-12...,your invoice of inr 25515.09 is due on 2025-12...,notify_human,\binvoice\b
2,Reminder: The client meeting is scheduled at 1...,reminder: the client meeting is scheduled at 1...,respond_or_act,\bmeeting\b
3,"Hello team, please find the attached weekly re...","hello team, please find the attached weekly re...",respond_or_act,\battached\b
4,"Hello team, please find the attached weekly re...","hello team, please find the attached weekly re...",respond_or_act,\battached\b
5,Your invoice of INR 38766.88 is due on 2025-12...,your invoice of inr 38766.88 is due on 2025-12...,notify_human,\binvoice\b
6,Congratulations! You have been selected as a l...,congratulations! you have been selected as a l...,ignore,\bcongratulations\b
7,Your order #6313 has been shipped and is expec...,your order #6313 has been shipped and is expec...,respond_or_act,default_fallback
8,"Dear user, we detected a login from a new devi...","dear user, we detected a login from a new devi...",notify_human,\bpassword\b
9,Your invoice of INR 32944.21 is due on 2025-12...,your invoice of inr 32944.21 is due on 2025-12...,notify_human,\binvoice\b
10,Reminder: The client meeting is scheduled at 1...,reminder: the client meeting is scheduled at 1...,respond_or_act,\bmeeting\b
11,Your order #3621 has been shipped and is expec...,your order #3621 has been shipped and is expec...,respond_or_act,default_fallback
12,"Hello team, please find the attached weekly re...","hello team, please find the attached weekly re...",respond_or_act,\battached\b
13,Reminder: The client meeting is scheduled at 1...,reminder: the client meeting is scheduled at 1...,respond_or_act,\bmeeting\b
14,Please complete the mandatory training module ...,please complete the mandatory training module ...,respond_or_act,default_fallback
15,"Hi, don't miss our sale with discounts up to 7...","hi, don't miss our sale with discounts up to 7...",ignore,\bsale\b
16,Reminder: The client meeting is scheduled at 1...,reminder: the client meeting is scheduled at 1...,respond_or_act,\bmeeting\b
17,"Hi, don't miss our sale with discounts up to 7...","hi, don't miss our sale with discounts up to 7...",ignore,\bsale\b
18,Please complete the mandatory training module ...,please complete the mandatory training module ...,respond_or_act,default_fallback
19,Please complete the mandatory training module ...,please complete the mandatory training module ...,respond_or_act,default_fallback

Sample notify_human rows:

,body,clean_text,triage_match
1,Your invoice of INR 25515.09 is due on 2025-12...,your invoice of inr 25515.09 is due on 2025-12...,\binvoice\b
5,Your invoice of INR 38766.88 is due on 2025-12...,your invoice of inr 38766.88 is due on 2025-12...,\binvoice\b
8,"Dear user, we detected a login from a new devi...","dear user, we detected a login from a new devi...",\bpassword\b
9,Your invoice of INR 32944.21 is due on 2025-12...,your invoice of inr 32944.21 is due on 2025-12...,\binvoice\b
24,Your invoice of INR 9983.71 is due on 2025-12-...,your invoice of inr 9983.71 is due on 2025-12-...,\binvoice\b
27,"Dear user, we detected a login from a new devi...","dear user, we detected a login from a new devi...",\bpassword\b

Sample respond_or_act rows:

,body,clean_text,triage_match
0,Reminder: The client meeting is scheduled at 1...,reminder: the client meeting is scheduled at 1...,\bmeeting\b
2,Reminder: The client meeting is scheduled at 1...,reminder: the client meeting is scheduled at 1...,\bmeeting\b
3,"Hello team, please find the attached weekly re...","hello team, please find the attached weekly re...",\battached\b
4,"Hello team, please find the attached weekly re...","hello team, please find the attached weekly re...",\battached\b
7,Your order #6313 has been shipped and is expec...,your order #6313 has been shipped and is expec...,default_fallback
10,Reminder: The client meeting is scheduled at 1...,reminder: the client meeting is scheduled at 1...,\bmeeting\b

Sample ignore rows:

,body,clean_text,triage_match
6,Congratulations! You have been selected as a l...,congratulations! you have been selected as a l...,\bcongratulations\b
15,"Hi, don't miss our sale with discounts up to 7...","hi, don't miss our sale with discounts up to 7...",\bsale\b
17,"Hi, don't miss our sale with discounts up to 7...","hi, don't miss our sale with discounts up to 7...",\bsale\b
28,"Hi, don't miss our sale with discounts up to 7...","hi, don't miss our sale with discounts up to 7...",\bsale\b
32,Congratulations! You have been selected as a l...,congratulations! you have been selected as a l...,\bcongratulations\b
34,Congratulations! You have been selected as a l...,congratulations! you have been selected as a l...,\bcongratulations\b

In [16]:
df['predicted_triage'] = df['clean_text'].apply(triage_rule)
df[['body','predicted_triage']].head()

                                                body predicted_triage
0  Reminder: The client meeting is scheduled at 1...   respond_or_act
1  Your invoice of INR 25515.09 is due on 2025-12...   respond_or_act
2  Reminder: The client meeting is scheduled at 1...   respond_or_act
3  Hello team, please find the attached weekly re...   respond_or_act
4  Hello team, please find the attached weekly re...   respond_or_act

In [17]:
# 6. Save results for submission
OUT = "data/milestone1_pranaya.csv"
df.to_csv(OUT, index=False)
print("Saved:", OUT)

Saved: data/milestone1_pranaya.csv

In [18]:
df[['body','predicted_triage']].to_csv('data/milestone2_output_pranaya.csv', index=False)