In [1]:
import pandas as pd
import nltk
import re

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\skgha\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
#2. Load Dataset

# We load the provided file sample_emails_with_triage_200.csv and display the first few rows to confirm successful loading.

df = pd.read_csv("../data/sample_emails_with_triage_200.csv")
df.head()

,id,sender,subject,body,priority,triage_label
0,1,alerts@bank.com,Password Reset Request,Reminder: The client meeting is scheduled at 1...,low,notify_human
1,2,alerts@bank.com,Congratulations! You've Won,Your invoice of INR 25515.09 is due on 2025-12...,low,respond
2,3,no-reply@service.com,Promotion: Big Sale,Reminder: The client meeting is scheduled at 1...,low,ignore
3,4,sales@shop.com,Monthly Report,"Hello team, please find the attached weekly re...",medium,respond
4,5,no-reply@service.com,Survey,"Hello team, please find the attached weekly re...",low,respond

In [ ]:
#3. Text Cleaning

# create a new column clean_text by:
#Converting all text to lowercase
#Removing punctuation, numbers, and special characters
#Keeping only alphabets and spaces




df['clean_text'] = (
    df['body']
    .astype(str)
    .str.lower()
    .str.replace('[^a-zA-Z ]', '', regex=True)
)

df[['body','clean_text']].head()

,body,clean_text
0,Reminder: The client meeting is scheduled at 1...,reminder the client meeting is scheduled at t...
1,Your invoice of INR 25515.09 is due on 2025-12...,your invoice of inr is due on please pay to ...
2,Reminder: The client meeting is scheduled at 1...,reminder the client meeting is scheduled at t...
3,"Hello team, please find the attached weekly re...",hello team please find the attached weekly rep...
4,"Hello team, please find the attached weekly re...",hello team please find the attached weekly rep...

In [ ]:
def triage_rule(text):
    t = str(text)

    if any(k in t for k in ['password', 'reset password', 'security issue']):
        return 'notify_human'

    if any(k in t for k in ['promotion', 'sale', 'offer', 'unsubscribe', 'newsletter']):
        return 'ignore'

    if any(k in t for k in ['invoice','payment','overdue','due on','meeting']):
        return 'respond_or_act'

    return 'respond_or_act'


 #Rule-Based Triage Logic:
 #High Priority — notify_human
 #Promotional Emails — ignore
 #Action Required — respond_or_act
 #If no rule matches, the default category is respond_or_act.

In [ ]:
df['triage'] = df['clean_text'].apply(triage_rule)
df[['clean_text','triage']].head()

#The triage function is applied to the cleaned text

                                          clean_text          triage
0  reminder the client meeting is scheduled at  t...  respond_or_act
1  your invoice of inr  is due on  please pay to ...  respond_or_act
2  reminder the client meeting is scheduled at  t...  respond_or_act
3  hello team please find the attached weekly rep...  respond_or_act
4  hello team please find the attached weekly rep...  respond_or_act

In [ ]:
df.to_csv("../data/milestone1_ayesha-naaz.csv", index=False)
print("Saved milestone1_ayesha-naaz.csv")

#the results are saved into: data/milestone1_ayesha-naaz.csv

Saved milestone1_ayesha-naaz.csv