In [15]:
import pandas as pd

In [16]:
# Load dataset
df = pd.read_csv("../data/email_evaluation_dataset_theertha.csv")

# Display preview
display(df.head())

,email_text,expected_action,expected_tone
0,"Hi Theertha, this is a reminder about our team...",notify,neutral
1,Reminder: Project review meeting today at 4 PM...,notify,urgent
2,This is a gentle reminder for our scheduled ca...,notify,polite
3,Our weekly sync-up meeting has been scheduled ...,notify,neutral
4,Please remember to attend the client meeting t...,notify,urgent

In [17]:
df = df.head(100)
df.shape

(100, 3)

In [18]:

df.to_csv("../data/email_evaluation_dataset_theertha.csv", index=False)

In [19]:
import re

def clean_email_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)   # remove punctuation & numbers
    text = re.sub(r'\s+', ' ', text).strip()  # remove extra spaces
    return text

In [20]:

df['clean_text'] = df['email_text'].apply(clean_email_text)

In [21]:
print("Clean_text column created successfully!")
display(df[['email_text', 'clean_text']].head())

Clean_text column created successfully!

,email_text,clean_text
0,"Hi Theertha, this is a reminder about our team...",hi theertha this is a reminder about our team ...
1,Reminder: Project review meeting today at 4 PM...,reminder project review meeting today at pm pl...
2,This is a gentle reminder for our scheduled ca...,this is a gentle reminder for our scheduled ca...
3,Our weekly sync-up meeting has been scheduled ...,our weekly syncup meeting has been scheduled f...
4,Please remember to attend the client meeting t...,please remember to attend the client meeting t...

In [22]:
def email_assistent(email_text):
    text = email_text.lower()

    # Urgent condition
    if "urgent" in text or "submit" in text or "deadline" in text:
        return "notify", "urgent"

    # thank you emails
    elif "thank you" in text:
        return "ignore", "polite"

    # Default case
    else:
        return "respond", "neutral"