In [7]:
import pandas as pd

# Load dataset
df = pd.read_csv("../data/email_evaluation_dataset_sinchana.csv")

# Confirmation message
print("Dataset loaded successfully!")

# Display preview
display(df.head())

Dataset loaded successfully!

,email_text,expected_action,expected_tone
0,Reminder: The project review meeting is schedu...,respond,polite
1,Your electricity bill for August is due by 25t...,respond,urgent
2,Newsletter: Top career tips for engineering st...,ignore,neutral
3,Server CPU usage has crossed 90%. Immediate at...,notify,urgent
4,"Hi, can you please share the updated project d...",respond,polite

In [3]:
df = df.head(100)
df.shape

(100, 3)

In [4]:
df.to_csv("../data/email_evaluation_dataset_sinchana.csv", index=False)

In [1]:
import re

def clean_email_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)   # remove punctuation & numbers
    text = re.sub(r'\s+', ' ', text).strip()  # remove extra spaces
    return text

In [4]:
df['clean_text'] = df['email_text'].apply(clean_email_text)

In [6]:
print("Clean_text column created successfully!")
display(df[['email_text', 'clean_text']].head())

Clean_text column created successfully!

,email_text,clean_text
0,Reminder: The project review meeting is schedu...,reminder the project review meeting is schedul...
1,Your electricity bill for August is due by 25t...,your electricity bill for august is due by th ...
2,Newsletter: Top career tips for engineering st...,newsletter top career tips for engineering stu...
3,Server CPU usage has crossed 90%. Immediate at...,server cpu usage has crossed immediate attenti...
4,"Hi, can you please share the updated project d...",hi can you please share the updated project do...

In [ ]:
def email_assistent(email_text):
    text = email_text.lower()

    # Urgent condition
    if "urgent" in text or "submit" in text or "deadline" in text:
        return "notify", "urgent"

    # thank you emails
    elif "thank you" in text:
        return "ignore", "polite"

    # Default case
    else:
        return "respond", "neutral"