In [7]:
import pandas as pd

df = pd.read_csv("../data/milestone1_sinchana.csv")
df.head()

,id,sender,subject,body,priority,triage_label,clean_text,triage,triage_match
0,1,alerts@bank.com,Password Reset Request,Reminder: The client meeting is scheduled at 1...,low,notify_human,reminder the client meeting is scheduled at t...,respond_or_act,\bmeeting\b
1,2,alerts@bank.com,Congratulations! You've Won,Your invoice of INR 25515.09 is due on 2025-12...,low,respond,your invoice of inr is due on please pay to ...,respond_or_act,\binvoice\b
2,3,no-reply@service.com,Promotion: Big Sale,Reminder: The client meeting is scheduled at 1...,low,ignore,reminder the client meeting is scheduled at t...,respond_or_act,\bmeeting\b
3,4,sales@shop.com,Monthly Report,"Hello team, please find the attached weekly re...",medium,respond,hello team please find the attached weekly rep...,respond_or_act,\battached\b
4,5,no-reply@service.com,Survey,"Hello team, please find the attached weekly re...",low,respond,hello team please find the attached weekly rep...,respond_or_act,\battached\b

In [2]:
print("Number of rows:", df.shape[0])

Number of rows: 200

In [4]:

df.columns

Index(['id', 'sender', 'subject', 'body', 'priority', 'triage_label',
       'clean_text', 'triage'],
      dtype='object')

In [5]:
df.head

<bound method NDFrame.head of       id                sender                      subject  \
0      1       alerts@bank.com       Password Reset Request
1      2       alerts@bank.com  Congratulations! You've Won
2      3  no-reply@service.com          Promotion: Big Sale
3      4        sales@shop.com               Monthly Report
4      5  no-reply@service.com                       Survey
..   ...                   ...                          ...
195  196  no-reply@service.com                Policy Update
196  197      boss@company.com                Order Shipped
197  198  no-reply@service.com            Weekly Newsletter
198  199     news@techblog.com              Payment Overdue
199  200     support@cloud.com          Promotion: Big Sale

                                                  body priority  triage_label  \
0    Reminder: The client meeting is scheduled at 1...      low  notify_human
1    Your invoice of INR 25515.09 is due on 2025-12...      low       respond
2    Reminder: The client meeting is scheduled at 1...      low        ignore
3    Hello team, please find the attached weekly re...   medium       respond
4    Hello team, please find the attached weekly re...      low       respond
..                                                 ...      ...           ...
195  Security alert: multiple failed login attempts...      low  notify_human
196  Your order #3828 has been shipped and is expec...   medium       respond
197  Congratulations! You have been selected as a l...   medium        ignore
198  Please complete the mandatory training module ...      low  notify_human
199  Congratulations! You have been selected as a l...      low        ignore

                                            clean_text          triage
0    reminder the client meeting is scheduled at  t...  respond_or_act
1    your invoice of inr  is due on  please pay to ...  respond_or_act
2    reminder the client meeting is scheduled at  t...  respond_or_act
3    hello team please find the attached weekly rep...  respond_or_act
4    hello team please find the attached weekly rep...  respond_or_act
..                                                 ...             ...
195  security alert multiple failed login attempts ...  respond_or_act
196  your order  has been shipped and is expected t...  respond_or_act
197  congratulations you have been selected as a lu...  respond_or_act
198  please complete the mandatory training module ...  respond_or_act
199  congratulations you have been selected as a lu...  respond_or_act

[200 rows x 8 columns]>

In [8]:
def triage_rule(text):
    text = text.lower()

    if "refund" in text or "urgent" in text or "password" in text:
        return "notify_human"

    if "newsletter" in text or "promotion" in text:
        return "ignore"

    return "respond_or_act"

df['triage'] = df['clean_text'].apply(triage_rule)
df[['body', 'triage']].head()

                                                body          triage
0  Reminder: The client meeting is scheduled at 1...  respond_or_act
1  Your invoice of INR 25515.09 is due on 2025-12...  respond_or_act
2  Reminder: The client meeting is scheduled at 1...  respond_or_act
3  Hello team, please find the attached weekly re...  respond_or_act
4  Hello team, please find the attached weekly re...  respond_or_act

In [9]:
df['predicted_triage'] = df['clean_text'].apply(triage_rule)
df[['body', 'triage', 'predicted_triage']].head()

,body,triage,predicted_triage
0,Reminder: The client meeting is scheduled at 1...,respond_or_act,respond_or_act
1,Your invoice of INR 25515.09 is due on 2025-12...,respond_or_act,respond_or_act
2,Reminder: The client meeting is scheduled at 1...,respond_or_act,respond_or_act
3,"Hello team, please find the attached weekly re...",respond_or_act,respond_or_act
4,"Hello team, please find the attached weekly re...",respond_or_act,respond_or_act

In [11]:
df[['body', 'predicted_triage']].to_csv("../data/milestone2_output.csv", index=False)

In [12]:
df.head(100)

,id,sender,subject,body,priority,triage_label,clean_text,triage,triage_match,predicted_triage
0,1,alerts@bank.com,Password Reset Request,Reminder: The client meeting is scheduled at 1...,low,notify_human,reminder the client meeting is scheduled at t...,respond_or_act,\bmeeting\b,respond_or_act
1,2,alerts@bank.com,Congratulations! You've Won,Your invoice of INR 25515.09 is due on 2025-12...,low,respond,your invoice of inr is due on please pay to ...,respond_or_act,\binvoice\b,respond_or_act
2,3,no-reply@service.com,Promotion: Big Sale,Reminder: The client meeting is scheduled at 1...,low,ignore,reminder the client meeting is scheduled at t...,respond_or_act,\bmeeting\b,respond_or_act
3,4,sales@shop.com,Monthly Report,"Hello team, please find the attached weekly re...",medium,respond,hello team please find the attached weekly rep...,respond_or_act,\battached\b,respond_or_act
4,5,no-reply@service.com,Survey,"Hello team, please find the attached weekly re...",low,respond,hello team please find the attached weekly rep...,respond_or_act,\battached\b,respond_or_act
...,...,...,...,...,...,...,...,...,...,...
95,96,no-reply@service.com,Weekly Newsletter,Your order #3634 has been shipped and is expec...,low,ignore,your order has been shipped and is expected t...,respond_or_act,default_fallback,respond_or_act
96,97,no-reply@service.com,Order Shipped,Security alert: multiple failed login attempts...,low,notify_human,security alert multiple failed login attempts ...,respond_or_act,default_fallback,respond_or_act
97,98,hr@company.com,Invoice Due,Security alert: multiple failed login attempts...,low,notify_human,security alert multiple failed login attempts ...,respond_or_act,default_fallback,respond_or_act
98,99,support@cloud.com,Payment Overdue,Notice: Your account will be locked unless ver...,low,notify_human,notice your account will be locked unless veri...,respond_or_act,default_fallback,respond_or_act
99,100,news@techblog.com,Order Shipped,Your order #4920 has been shipped and is expec...,medium,respond,your order has been shipped and is expected t...,respond_or_act,default_fallback,respond_or_act

In [13]:
df['clean_text'].head(100)

0     reminder the client meeting is scheduled at  t...
1     your invoice of inr  is due on  please pay to ...
2     reminder the client meeting is scheduled at  t...
3     hello team please find the attached weekly rep...
4     hello team please find the attached weekly rep...
                            ...
95    your order  has been shipped and is expected t...
96    security alert multiple failed login attempts ...
97    security alert multiple failed login attempts ...
98    notice your account will be locked unless veri...
99    your order  has been shipped and is expected t...
Name: clean_text, Length: 100, dtype: object

In [14]:
# select 100 test mails
eval_df = df.sample(100,random_state=42)
eval_df = eval_df.reset_index(drop=True)
eval_df.head()

,id,sender,subject,body,priority,triage_label,clean_text,triage,triage_match,predicted_triage
0,96,no-reply@service.com,Weekly Newsletter,Your order #3634 has been shipped and is expec...,low,ignore,your order has been shipped and is expected t...,respond_or_act,default_fallback,respond_or_act
1,16,news@techblog.com,Payment Overdue,"Hi, don't miss our sale with discounts up to 7...",low,notify_human,hi dont miss our sale with discounts up to on...,respond_or_act,\bsale\b,respond_or_act
2,31,news@techblog.com,Weekly Newsletter,Notice: Your account will be locked unless ver...,high,notify_human,notice your account will be locked unless veri...,respond_or_act,default_fallback,respond_or_act
3,159,no-reply@service.com,Welcome to Service,Reminder: The client meeting is scheduled at 9...,low,respond,reminder the client meeting is scheduled at t...,respond_or_act,\bmeeting\b,respond_or_act
4,129,sales@shop.com,Invoice Due,Your order #6464 has been shipped and is expec...,low,respond,your order has been shipped and is expected t...,respond_or_act,default_fallback,respond_or_act